package-lock.json, test/integration/reffy-reports.js
This depends on the real data scraped from specs and would fail if
specs are reorganized, so the picked examples are ones which are very
unlikely to change.
=> Add smoke test for reffy-reports integration

.github/main.workflow
The action returning neutral counts as failure and will cancel
anything that runs in parallel to it. Make it depend on everything
before it to avoid this. Also make lint run in parallel to build since
it shouldn't depend on it.
=> Make the GitHub actions master filter depend on everything before it

build.js, test/unit/build.js
Broken by https://github.com/foolip/mdn-bcd-collector/pull/28 and not
noticed because there were no tests.
=> Fix and test IDL static operations after webidl2.js upgrade

build.js, package.json
Unhandled promise rejections don't have the error stack, so
`--throw-deprecation` isn't very helpful for debugging.
=> Catch and log errors in build.js

.github/workflows/pull_request.yml, .github/workflows/push.yml
No need to have deploy blocked on lint, or to have deploy listed in
PRs at all. Presumably there's a template system coming to share
steps.
=> Split push and pull_request workflows in GitHub Actions

build.js, static/resources/harness.js, test/unit/build.js
This PR fixes a number of issues in the 0.0.2 commit just before, namely:
- Service workers require secure contexts
- Web workers and service workers generated odd results if they weren't supported
- Fix CSS prefix reports
- Disable CSS prefix generation in build.js
=> Fix issues in results generated by 0.0.2

DESIGN.md
It appears the reports section in `DESIGN.md` wasn't updated to mention where the reports are being stored.  This fixes that, adding content to the section.
=> Add reports section to DESIGN.md

build.js, test/unit/build.js
This PR adds numerous unittests to cover more lines within build.js, leaving only the file generation functions untested.
Before:
File              | % Stmts | % Branch | % Funcs | % Lines
------------------|---------|----------|---------|---------
All files         |    66.9 |    65.96 |   68.75 |   67.22
build.js         |   51.03 |    61.74 |   52.38 |   50.72
After:
File              | % Stmts | % Branch | % Funcs | % Lines
------------------|---------|----------|---------|---------
All files         | 79.58 (+12.68) |    87.23 (+21.27) |   77.78 (+9.03) |   79.62 (+12.4)
build.js         |   69.93 (+18.9) |    88.59 (+26.85) |   65.85 (+13.47) |   69.49 (+18.77)
=> Add more unittests for build.js

DESIGN.md, build.js, test/unit/build.js
Part of work for #333.  This PR introduces support for implementing custom tests for CSS properties.  If a custom test is implemented, it disables the default tests.
=> Create custom CSS property test support

build.js, test/unit/build.js
This PR introduces support for testing various nonnamed members, allowing testing of constructors, and expanding members in `iterable<>`, `maplike<>`, and `setlike<>`.
=> Add support for testing nonnamed members

build.js, custom-tests.json, non-standard.idl, package.json, static/resources/harness.js, test/unit/build.js
This PR introduces some new testing additions.  Specifically:
- Support for testing constructors
- Support for iterable/maplike/setlike APIs
- Support for testing dictionaries
- Add more non-standard APIs
- Add test for CSS custom variables
=> Constructor, iterable/maplike/setlike, and dictionary tests + more non-standard APIs

package-lock.json, test/selenium/selenium.js
This limits the browser versions tested via Selenium to those released on/after Jan. 1st, 2015 (with the exception of IE/Edge, which is set to IE 11 and all versions of Edge).
=> Limit browsers tested via Selenium

github.js, test/unit/github.js
This PR prepends the app version to the filenames sent to the results repository, allowing for easier organization.
=> Add appversion to filenames sent to results repo

static/resources/harness.js
This PR introduces some improvements to service worker tests, including simplification of the `__workerCleanup` function and awaiting the promise completion of the initial cleanup (which may have been causing async timing issues causing #357).  This also adds some logging statements to test the issues in production (a bit hard to test on local due to lack of HTTPS).
=> Improve service worker tests

build.js, package-lock.json, package.json, static/resources/harness.js, static/resources/serviceworker.js
This PR fixes issues with service worker based tests on older browsers (such as Chrome 40).  By eliminating the use of the BroadcastChannel "polyfill" and switching to the same methods used for web workers (global `onmessage` which routes the data to a function made within the promise to resolve said promise).
=> Fix service worker tests on older browsers

build.js
This PR replaces a few uses of the array contact method with spread syntax, as per the review in https://github.com/foolip/mdn-bcd-collector/pull/339#discussion_r468567881.
=> Prefer spread syntax over concat method

static/resources/harness.js
This PR adds some lines to harness.js to catch the error messages generated by pre-Chromium Edge for constructor issues.
=> Update harness.js to catch pre-Chromium Edge errors for constructors

.eslintrc.json, package-lock.json, package.json, test/selenium/selenium.js
This PR adds `babel-eslint` and sets it as the ESLint parser.  This will allow for proper destructuring syntax parsing.
=> ESLint improvements

update-bcd.js
This PR updates the BCD update script with a few things, namely the following:
- Initialize support matrix with all browsers in BCD data -- this allows us to better determine version numbers, due to the improvement listed right below
- Improved null value handling -- if support changes between versions and there are null/unknown values in between, do not determine a version number
- Make sure there are no duplicate statements -- when adding a statement including `version_removed`, sometimes it will add a duplicate; this was resolved
- Add prefix support -- account for prefixed support in browsers
=> Update the BCD updater

.eslintrc.json, update-bcd.js
This PR improves the version omission when there are null gaps in `update-bcd`.
=> Improve version omitting in update-bcd

app.js, build.js, package-lock.json, package.json, static/index.html, static/resources/harness.js, test/app/tests.js, test/unit/build.js, tests.js
This PR updates the scripts to allow for individual tests (fixes #376).  The build script generates individual test files for each interface and CSS property that can be accessed for manual testing.  A dropdown is added to the homepage to allow for quickly getting to a specific test.
=> Generate individual API/CSS tests

build.js
This provides a few hotfixes to the most recent 0.0.6 upgrade that resolves some test generation.  Namely, the following:
- All individual tests are generated in folders to allow for any number of subtests
- CSS individual tests now generate both methods
=> Fix individual test generation

find-missing.js, package.json
This PR adds a `find-missing` script to compare what's in BCD but not our tests.
=> Add find-missing script

custom-tests.json
This PR adds a custom test for the MediaDevices API to test the instance exposed via `navigator.mediaDevices`.
=> Add custom test for MediaDevices API

selenium.js
This PR adds a try-catch clause around the Selenium script's operation, so that it will not only close the driver on error (thus refraining from wasting automation minutes), but also so that if one browser version crashes, the script still runs through the rest.
=> Catch errors during Selenium run

app.js, tests.js, unittest/app/app.js
First checking if there were endpoints and then getting the tests was
doing double/unnecessary work.
=> Simplify the lookup of tests for /tests/*

static/resources/harness.js
This PR fixes two worker-related issues:
- The workers attempted to set service worker helpers within the workers, preventing the crash of the tests.  This safeguards the helpers by checking if `window` exists.
- A "no worker support" message will no longer appear, and workers will not be set up, if there are no worker tests.  (Fixes #448)
=> Workers hotfixes

update-bcd.js
This PR fixes a condition within the BCD updater for when the first browser version we have results for isn't the first browser version.
=> Fix condition within update-bcd

selenium.js
This PR fixes the Selenium script to catch when an initial run crashes during steps like the configuration stage, rather than just within the individual run.  This will prevent the whole script from crashing if the Selenium server doesn't support a specific configuration (like Edge 12).
=> Catch crash of individual Selenium run on configuration

static/resources/harness.js, static/resources/serviceworker.js
This PR fixes communication with service workers due to lack of support for certain features.  By using the `MessageChannel` API, which by BCD was supported in all browsers before Service Workers were supported, we can now get messages from service workers in any browser.
Fixes #453.
=> Use MessageChannel API to handle messaging with Service Worker

selenium.js
This PR tells the Selenium script to await the driver build, rather than creating an uncaught promise rejection.
=> Hotfix for Selenium misconfiguration errors

DESIGN.md, build.js, package-lock.json, package.json
This PR updates the custom test generation to use normal test generation for constructors if a custom constructor test isn't defined.  This resolves all constructors for interfaces with custom tests resulting in `false`.  Found in cases like `api.AudioBuffer.AudioBuffer`.
(Bumps patch version since it resolves a bug in test results.)
=> Adjust custom tests to account for constructors better

.github/workflows/push.yml, app.js, app.staging.yaml, storage.js, unittest/unit/storage.js
To make this work, create a new app.staging.yaml which deploys to a
different service. Versions are again left unspecified, which means that
new versions will be created for each deploy.
=> Use different buckets for production and staging

.github/workflows/push.yml, app.staging.yaml, app.yaml
Updating getHost in app.js to use GAE_SERVICE instead of GAE_VERSION it
became apparent that determining the host name from the service would be
dubious. Every version in default would map to
mdn-bcd-collector.appspot.com and every version in staging would map to
staging-dot-mdn-bcd-collector.appspot.com, making it pointless to have
multiple versions.
And indeed it is. It's just a bit ugly to spell out the version in
push.yml, because it can't be specified in app.yaml. Whatever.
=> Go back to using a single service (default) and two versions (staging/production)

static/resources/harness.js, views/results.ejs
This PR updates the error handling a little better to prevent client crashes, by doing the following:
1) Catch 4xx errors as well as 5xx errors
2) If no parseable JSON, set `response.error` to the response's text
=> Handle server errors in harness.js and results pages better

views/index.ejs
This PR wraps the input elements in a `form` element rather than a `div`, allowing clients to use the Enter key to submit and start the tests.
=> Use form on homepage (allow "Enter" to run tests)

app.js, tests.js, unittest/app/app.js
The computed host is unused in tests.js since https://github.com/foolip/mdn-bcd-collector/pull/416.
=> Remove the unused getHost() helper

static/resources/harness.js
This PR updates the results posting so that, rather than check if the error code is 400 or greater, it checks exclusively for 200 to confirm success.
=> harness.js: handle status code better

update-bcd.js
This PR loosely maps the UA string of Samsung Internet in `update-bcd.js`.
=> Add Samsung Internet to getBrowserAndVersion() in update-bcd.js

build.js, unittest/unit/build.js
This PR reverts an update that has each member test to make sure that the API is `true`, so that if the API is `false`, the members are `null`.
=> Don't test for "instance in self" for members

README.md, nodemon.json, package.json
This PR configures `npm run start-dev` to rebuild the tests on file changes, making development slightly easier.
=> Have start-dev command rebuild automatically

custom-idl/webgl.idl
This adds [LegacyNoInterfaceObject] and the WebGLTimerQueryEXT
interface.
=> Sync WebGL extensions with their specs

DESIGN.md, build.js, custom-tests.json, unittest/unit/build.js
This PR fixes #500 by implementing a syntax to import the custom test code from other APIs and their members with a simple syntax of `<%ident:varname%>`, where the `ident` is the identifier to copy from, and the `varname` is what to rename the `instance` variable to.  This also updates the audio node code to use this new syntax.
=> Custom tests import support

build.js, custom-tests.json, unittest/unit/build.js
This PR adds linebreaks to the custom tests to improve their display, making them more legible, like so:
=> Add linebreaks to custom tests for better display

build.js, unittest/unit/build.js
This PR moves the test importing, function wrapping, and code formatting for custom tests into its own function, allowing it to be used in all custom test functions.
=> Create compileCustomTest function

package-lock.json, package.json
Since we've added some new functionality, this preemptively bumps the version number to 0.3.0 for the next production release.
=> Bump version number to 0.3.0

update-bcd.js
This PR changes `update-bcd` to, rather than produce `true` if data is inconclusive, generate a range.  While this will cause the BCD linters to always fail, a reviewer can narrow it down better later.
=> Always generate ranges for update-bcd

update-bcd.js, utils.js
This PR moves a few useful functions from the `update-bcd` script into the new `utils` to allow for other scripts to use them if/when needed.
=> Move a few functions from update-bcd.js to utils.js

build.js, find-missing.js, package-lock.json, package.json, selenium.js
This PR bumps the version number to 0.3.1 and upgrades BCD to the new 2.0.0 release.
=> Bump version number and upgrade to BCD 2.0.0

update-bcd.js
This PR provides a number of updates to the `update-bcd` script to improve its performance, including the following:
- If a version number in BCD doesn't contradict a generated range, don't replace it with the range
- Remove a version_removed if proven wrong
- Account for the support of the parent (fixes #506)
=> Improve update-bcd

github.js
This PR reverts a change to use utils.js in the GitHub module, fixing production.
=> Don't include utils.js in production

.github/workflows/pull_request.yml, logger.js
To make it possible to start with NODE_ENV=production outside of GAE,
tweak the logic in logger.js.
=> Test NODE_ENV=production to get closer to the real deal

.gitattributes
Git for Windows uses CRLF by default while the eslint configuration requires LF. This makes sure git uses LF regardless of local git configuration.
=> Force LF when checking out

static/resources/harness.js
When attempting to run the Selenium script on Safari, I noticed that the tests wouldn't run, and they'd simply timeout.  After further review, it seems that the audio resources weren't loading for some odd reason.  This PR sets a five-second timeout to start the tests regardless of whether or not the resources have all loaded.
=> Start tests even if all resources don't load

update-bcd.js
Cherry-picked from #553.  This makes the prefix an empty string if there is none.
=> Always include prefix key in results of support map/matrix

selenium.js
This PR fixes an update to use the logger, which doesn't support substitution strings.
=> Don't use substitution in logging

unittest/unit/update-bcd.js, update-bcd.js
Fixes https://github.com/foolip/mdn-bcd-collector/issues/562.
=> Revamp getBrowserAndVersion to handle Safari iOS and Samsung Internet

unittest/unit/update-bcd.js
This adds an additional unittest for the update-bcd script when results are all null.
=> Add unittest for all-null API

DESIGN.md, build.js, custom-tests.json, package-lock.json, package.json, static/resources/harness.js, unittest/unit/build.js, views/tests.ejs
This PR updates the resources for custom tests in two main ways:
1) Rather than redefining resources per each and every API, this adds a `__resources` entry underneath `api`, where each interface will reference their keys to load them
2) Adds reusable instances as resources to eliminate issues found when creating too many Web Audio APIs (like AudioContext)
=> Improve resources and add reusable instances as a resource

.github/workflows/pull_request.yml, package.json, scripts.js, unittest/puppeteer/harness.js
Bit longer but better portability.
Closes #546
=> Port bash scripts to JS

package.json
=> start-dev command: use double quotes for Windows compatibility

app.js, static/resources/harness.js, unittest/app/app.js, views/index.ejs
This PR performs a few compatibility updates to improve compatibility with Internet Explorer:
- Patches console being undefined when IE DevTools are closed
- Moves test URL generation server-side (IE 8 and below don't support form.onsubmit -- this also reduces client-side JavaScript)
Confirmed full compatibility*: IE 7, Safari 3, Firefox 1, Chrome 1, Opera 9.5
_* Full compatibility includes form submission, test operation, result rendering, result submission, and GitHub submission.  Does not include datalist and styling._
=> Improve compatibility for Internet Explorer

find-missing.js, unittest/unit/find-missing.js
This PR updates the code in `find-missing.js` to allow for reversing the direction of missing entries (so we can find what's in the collector but not in BCD).  It is not hooked up to any command line arguments yet -- that will be done in a follow-up PR to refactor everything to use `yargs`.
=> Allow for reversing direction of find-missing

unittest/unit/build.js, unittest/unit/find-missing.js, unittest/unit/github.js, unittest/unit/update-bcd.js
This PR prevents `proxyquire` from loading the original files or modules, thus resolving the issue mentioned in https://github.com/foolip/mdn-bcd-collector/pull/553#discussion_r495793082.
=> Prevent callThru on proxyquire

views/testnotfound.ejs
This PR fixes a slight issue with the regex in the did-you-mean suggestions when tests aren't found.
=> Use global regex for did-you-mean suggestion

custom-tests.json
This PR updates the WebGL reusable instance to get a WebGL2 context when able.  WebGL2 contexts inherit all WebGL1 extensions, so we do not have to worry about testing them separately.
Inspried by https://github.com/mdn/browser-compat-data/pull/6840#discussion_r501871182.
=> Get WebGL2 context when able

app.js, build.js, find-missing.js, github.js, selenium.js, update-bcd.js
This PR simplifies the module exports, removing them from the `else {}` clauses.
=> Simplify module.exports

selenium.js
This PR upgrades the Selenium script to enhance testing between OSes and OS versions, by testing browsers in both Windows and macOS (aside from Safari which will only run in macOS), as well as testing in the most recent Windows versions and falling back to older versions when needed.
=> Selenium upgrades: multiple OS support

README.md, nodemon.json, package.json, scripts.js
This PR provides some updates to improve development, such as auto-copying `secrets.sample.json` to `secrets.json` when needed, ignoring `scripts.js` on the dev server rebuild watcher, and running `npm i` before starting the dev server.
=> Update prepare stage, Nodemon rules, and npm run start-dev

static/resources/harness.js
This PR exposes the `reusableInstances` variable to make it easier to debug issues in the console.
=> Expose reusable instances globally

selenium.js
This PR reverses the order of browsers when collecting with the Selenium script, so that it collects the results for the newest first.
=> Reverse browser version order (collect newest versions first)

app.js, views/tests.ejs
This PR adds a `blacklist` parameter to the test running URL to disable specific tests when running all of them.  This is to allow us to disable certain APIs for Chrome versions when they crash the browser, so we can still obtain other data for the other APIs.
=> Add blacklist functionality to disable certain tests

custom-tests.json
This PR fixes the HTML element API tests by testing if the constructor is not `HTMLUnknownElement` __or__ `HTMLElement` (before, it only tested if it's not `HTMLUnknownElement`, which causes issues when the browser doesn't support `HTMLUnknownElement`).
=> Fix tests for HTML element APIs

custom-tests.json
This PR changes the HTML and SVG element API constructor confirmation to make sure the API names are exclusively the expected ones, rather than if it's not `HTMLUnknownElement`, `HTMLElement`, or `SVGElement`.
=> HTML/SVG elements: improve API confirmation

.github/workflows/push.yml
This PR reworks the `push` GitHub Action to deploy a new production version every time that the version number is bumped in the `main` branch.  Now, rather than pushing to `prod` ourselves, the GitHub Action will push to `prod` to let us know where it's at.
=> Deploy new prod on version bump

.github/workflows/push.yml
This PR adds the missing Action version number to the new Action changes.
=> Fix new import in GitHub Action

.github/workflows/push.yml
This PR names each of the deploy stages in the `Push` GitHub Action for convenience (and since the default name is only the first run command, which looks weird on the production deployment).
=> Add names to each deploy stage in push action

app.js, static/resources/style.css, views/index.ejs
This PR includes the app version in the title section on the homepage.  Useful to ensure a production version is successfully deployed.
=> Show app version on homepage

selenium.js
Oddly enough, it seems that SauceLabs and BrowserStack have different capability names for the OS.  This PR updates the capability to accommodate for these differences.  Furthermore, this adds exact macOS versions to test with on both BrowserStack and SauceLabs.  Finally, since BrowserStack doesn't support the x.0 Safari versions (it supports 10.1 but not 10.0), this returns an error as such.
=> Improve platform versioning between SauceLabs and BrowserStack

static/resources/harness.js
In Chrome 2-5, the Worker has a frustratingly weird way to indicate lack of support.  Rather than the variable not being defined, attempting to construct it throws a SyntaxError.  To accomodate for it, this PR works the Worker and ServiceWorker testing to try and construct it if it can, if not then classify it as unsupported.
=> Check to make sure workers construct properly

selenium.js
This PR fixes two issues with the Selenium script:
1) BrowserStack was setting an OS version for Safari, however Safari is dependent on the OS version -- this makes sure BrowserStack won't enforce an OS version for Safari
2) Versions to test weren't sorted properly (particularly for Safari) -- this fixes the sorting
=> Selenium fix

custom-tests.json
This PR reworks the tests for the HTML and SVG element APIs to only confirm that it's the correct API (not its parent) on the main instance test (since we only need to do it once).  This also lets us avoid an issue in IE 7 that prevents us from confirming if the element-specific API is implemented and not just the main `HTMLElement` API.
=> Only verify HTML/SVG element APIs on the main instance test

selenium.js
This PR offsets a nasty Safari WebDriver bug where Safari will report that the URL has changed before it has even unloaded the former page by awaiting for the _element_ to load (rather than just the page alone).
=> Selenium: await status element on test page

selenium.js
It turns out that BrowserStack has another error when the browser configuration is unsupported.  This PR updates the Selenium script to account for it.
=> Account for other BrowserStack unsupported error

README.md, secrets.sample.json, selenium.js
This PR gives the Selenium a slight refactor so that it handles multiple Selenium grids.  Since both SauceLabs and Browserstack both support certain browser versions that the other one doesn't, this will ensure the most browser coverage with a single run.
=> Selenium: refactor to handle multiple grids

custom-tests.json
This PR fixes a boolean for the SVG element tests that accidentally inverts support.
=> Fix SVG element tests

package.json
This PR fixes the version number for the `didyoumean` dependency by removing the caret, making it consistent with the other dependencies.﻿
=> Remove caret in version for "didyoumean"

app.js, views/results.ejs
This PR provides a few compatibility fixes that improve support for Firefox 1-4 and Internet Explorer by performing the following:
- Adds the apparently-required `body` argument to the `XMLHttpRequest.send()` command
- Removes JSON exchange and uses status codes + strings for results and GitHub export page
=> Compat fixes

package-lock.json, package.json
This PR switches the source of `webref` back to @foolip's fork, selecting the new update branch that was recently pushed.﻿
=> Switch webref branch back to foolip's fork

selenium.js
BrowserStack doesn't support Edge 12-14 or Safari x.0 versions.  However, instead of returning an "unsupported" error, instead it remaps them to the closest match (Edge 12-14 -> Edge 15, and Safari x.0 -> x.1).  This PR includes a few if clauses to mitigate these issues.
=> Ignore versions BrowserStack doesn't support but remaps instead

custom-tests.json
This PR updates the custom test for the `HTMLTableCellElement` API for better IE/Edge support.  Turns out that IE calls the API `HTMLTableDataCellElement` instead; this test accommodates for this other name.﻿
=> Fix custom test for HTMLTableCellElement for IE

custom-tests.json
This PR updates the custom tests for the SVG element APIs.  Some of the APIs we were testing were not exposed directly, but are base interfaces for other interfaces, unexposed on their own -- this PR fixes this issue.﻿
=> Update custom tests for SVG elements

custom-tests.json
This PR optimizes the custom tests for the `Element` and `HTMLElement` APIs.
For `HTMLElement`, by specifying a non-existent tag name, we're able to confirm what is supported on the `HTMLElement` API, rather than a specific element's API.
For `Element`, by specifying an empty namespace on `document.createElementNS()`, it will just create a generic element (non-HTML), so we can confirm what's on the `Element` API and not just the `HTMLElement` API.
=> Optimize Element and HTMLElement custom tests

selenium.js
This PR fixes the OS version selection for Safari 12.0.  Apparently, SauceLabs set 12.0 to macOS Mojave, rather than High Sierra.﻿
=> Fix macOS version for Safari 12.0 in Selenium script

ua-parser.js, unittest/unit/ua-parser.js, update-bcd.js
This PR renames the `getBrowserAndVersion` function to `parseUA`.﻿
=> Rename getBrowserAndVersion to parseUA

ua-parser.js, unittest/unit/ua-parser.js, unittest/unit/update-bcd.js, update-bcd.js
This PR updates the UA parser to return a like-null dictionary when the UA string cannot be parsed (such as in the cases of unittests).
=> Return "null" if UA cannot be parsed

build.js
This PR adds support for the `LegacyFactoryFunction` extended attribute, which can have constructors under names different from the interface name.  (An example of this is `api.HTMLAudioElement.Audio`, where the interface defines the `Audio()` constructor.)﻿
=> Add support for LegacyFactoryFunction constructors

custom-idl/html.idl
This PR removes the temporary IDL for `api.Element.accessKey`, since it has been removed from BCD.﻿
=> Remove IDL for Element.accessKey

build.js
This PR updates the custom test generation to avoid accidentally generating custom tests for common members like "toString".﻿
=> Fix custom test generation for common members (like "toString")

selenium.js
This PR maps Safari 6.1 properly to accommodate for BrowserStack having Safari 6.2 instead.﻿
=> Accommodate for Safari 6.1 in Selenium

app.js, unittest/app/app.js
The package version is exposed on the environment, I found -- this PR simplifies our code to use the environment variable.
=> Use process.env.npm_package_version vs. require('./package.json').version

unittest/puppeteer/harness.js
Something is causing issues with running Firefox in the Puppeteer unittests on macOS CI (it is working totally fine in local though).  This PR disables testing Firefox in Puppeteer.
=> Disable testing Firefox in unittests

build.js
This PR adds a console error when build.js determines a custom test is malformed for any reason (syntax errors, bad import, etc.), along with rather than just crashing the build on a syntax error.
=> Throw a console.error in build.js if custom test is malformed

views/index.ejs
This PR adds a mention that event interface testing is not accurate.
=> Mention caveat about event interfaces

build.js, static/resources/harness.js, static/resources/serviceworker.js, static/resources/sharedworker.js, static/resources/worker.js
This PR improves the test code for better Promise-based support, by doing the following:
- Consolidating and flattening functions, thus simplifying their code
- Processing a promise rejection as an error
- Check for a thenable object, rather than explicitly a promise
- Remove redundant Promise.resolve()
- Remove redundant promise wrapping
=> Improve testing code for better promise support

custom-tests.json
This PR adds custom tests for the CSSFontFaceRule and CSSImportRule APIs, to help add data for https://github.com/vinyldarkscratch/browser-compat-data/pull/23.﻿
=> Add custom tests for CSSFontFaceRule and CSSImportRule

build.js, static/resources/harness.js
This PR fixes some issues around testing with promises, by doing two things:
- Catches when a promise fails (using .catch())
- Wraps _everything_ in functions, for when promise and non-promise code is combined
=> Fix issues with testing with promises

custom-tests.json, selenium.js, static/resources/harness.js
This PR provides a number of compatibility and stability fixes, especially around promises.
- Asynchronously quit drivers in Selenium
- Update Crypto + CryptoKey code
- Increase timeout before showing possible failure message
- Call runTest in parallel
- Accommodate for dumb IE8 parsing issue
- Cleanup service worker after test completion
- Call promise.then(() => {}) on promises used in imports
- Only cleanup when needed
- Fix linting
=> Various fixes

static/resources/harness.js
In the styling updates, I had set the test running pages to use the main layout.  Initially, we wanted to ensure that we're not loading too many resources before running the tests, however a) since users visit the homepage as it is, the CSS is already cached and loaded, and b) some older browsers were actually crashing trying to re-render the page after changing fonts.  I initially forgot to remove the loading code that loads the CSS styling after tests run.
=> Don't double-load style.css after test run

app.js, custom-tests.json
Though not required as the tests will run regardless, this PR adds a `text/event-stream` resource that is loaded by `api.EventSource`, which gets rid of the annoying "wrong content type" errors.
=> Fix test for api.EventSource

custom-tests.json
The test for the BatteryManager API causes freezes, which crashes the tests.  For now, this disables its custom test.﻿
=> Disable test for BatteryManager

app.js, github.js, unittest/app/app.js
This PR configures the appversion to be the trimmed hash of the git HEAD﻿when running in dev or staging builds.
=> Use git commit hash as version in dev/staging

app.js, selenium.js, static/resources/style.css, unittest/app/app.js, views/index.ejs, views/tests.ejs
This PR replaces the hidden `hide-results` checkbox with a `hidden` input that is added when `?selenium=true` is present on loading the homepage.﻿
=> Upgrade Selenium to auto-hide results

app.js, github.js, unittest/app/app.js, unittest/unit/github.js
Looks like we can't get the git commit hash on staging, so this simply uses "Dev" as the version.﻿
=> Use "Dev" as version on local/staging versions

selenium.js
Turns out that the verbose logger being temporarily used already has timestamps!
=> Remove redundant timestamp in Selenium script's log() function

selenium.js
This PR simplifies the order of the browser versions in the Selenium script, by removing the use of .reverse() and simply sorting in the intended direction.
=> Simplify order of browsers to test in Selenium script

update-bcd.js
This PR renames the "files" argument to "reports" internally, as well as adds a new `--category/-c` argument to limit the affected data category (ex. `api` or `css.properties`).
=> Update update-bcd arguments

unittest/unit/update-bcd.js, update-bcd.js
This PR improves the error thrown when a report has no results, including the user agent so that we can narrow down which report is the problematic report.
=> Improve error when a report has no results

static/resources/harness.js
Apparently, some of Firefox's old exceptions are objects with "result" and "message" properties, and are not `Error` instances.  This PR updates the value processor to catch these old exceptions.
=> Accommodate for old-style Firefox NS_ERROR exception

ua-parser.js, unittest/unit/ua-parser.js
This PR makes the UA parser a little more lenient on the last version iteration.  Rather than comparing both major and minor versions, this only compares the major version.  (ex. if we have `["13", "13.3", "14"]`, and our version is `14.2`, return `14`)
Fixes #774.
=> UA parser: more lenient version matching on last version

static/resources/harness.js
This PR performs a number of optimizations, logging increases, and code cleanups to improve the harness.js script.
- Use a "state" variable vs. resources.testsStarted
- Catch multiple test completions and error to console
- Add "current exposure" state
- Add state.timedout
- Decrease timeout to 20 seconds (originally 30)
- Catch multiple test completions per exposure scope
- Don't pass the "results" array through all of the test scopes
- Fix exposure setting to always set regardless of test presence
- Lint
=> Improve performance for harness.js

build.js, unittest/unit/build.js
This PR fixes tests for constructors with names other than the constructor's name.﻿
=> Fix tests for LegacyFactoryFunction-based constructors

github.js, selenium.js, unittest/unit/github.js, update-bcd.js
This PR fixes #790.  To reduce file size, this uses GZip compression for the results JSON when saving them.  There are practically no performance drawbacks as a result.
=> Compress results JSON with GZip compression

github.js, selenium.js, unittest/unit/github.js
This PR shrinks the JSON reports into compact versions without whitespace.  Since the files are meant to be read by machine, there's not really much reason to beautify the JSON.  (We can beautify as needed.)﻿
=> Compact report JSON

.github/workflows/push.yml
This should prevent failing deploy steps due to multiple pushes within five minutes.
=> Add "max-parallel: 1" to deploy step in push

unittest/unit/update-bcd.js, update-bcd.js
This PR improves our generated ranges.  A while back, we introduced generating ranges for when we don't know the exact version, however we were only generating one half of a range.  This led to the issue of not updating some inaccurate data, as well as checking the versions in the collector when mirroring.  For example: we generate the range of "≤19" based upon data from Chrome 17 (false), 18 (null), and 19 (true) -- if Chrome is set to "2" in BCD, however, the updater will ignore it even though we can confirm the data is inaccurate.  Now, this generates ranges such as "17> ≤19" (whilst still generating ranges like "≤4" if we don't have results for all the prior versions since the first browser release), so that we can catch additional invalid data.
=> Update BCD: improve ranges

unittest/unit/update-bcd.js, update-bcd.js
This PR introduces a command line argument that allows for filtering the browsers to modify.
=> Allow for filtering browsers in update-bcd

custom-idl/html.idl
This is a capitalization typo:
https://github.com/mdn/browser-compat-data/pull/7402#discussion_r527274048
=> Remove formEncType and lowSrc custom IDL

find-missing.js, unittest/unit/find-missing.js
This PR updates the arguments to the find-missing script in two ways:
- Fixes the direction argument and its results for clarity
- Adds a category argument to filter results by category
=> Update arguments to find-missing script

build.js
This PR fixes #825 by telling static attributes not to generate custom tests by default, only when a custom test is explicitly written.﻿
=> Don't auto-generate custom tests for static attributes/methods

custom-tests.json
Reading more on the [`ANGLE_instanced_arrays` documentation](https://developer.mozilla.org/en-US/docs/Web/API/ANGLE_instanced_arrays), it appears that it is available as an "extension" only in WebGL1.  "In WebGL2, the functionality of this extension is available on the WebGL2 context by default and the constants and methods are available without the "ANGLE" suffix."
This PR updates the custom tests to test the non-suffixed versions directly from the WebGL2 contexts.
=> Fix tests for ANGLE_instanced_arrays

custom-idl/html.idl
This PR removes the duplicate, miscapitalized entries for the HTMLMarqueeElement interface.﻿
=> Remove miscapitalized entries

add-new-bcd.js, nodemon.json, package.json, update-bcd.js
This PR introduces a new script that adds new BCD entries based upon what is currently missing but is in spec, and has support in at least one browser as per the collector results.
=> Create add-new-bcd script

static/resources/harness.js, static/resources/style.css
This PR updates the styling for the results upon test completion to consolidate screen space using the `<details>` element to make the code display a dropdown, along with a few other enhancements (such as coloring the result green/red based upon the value).
Before:
After:
=> Update styling for results display

static/resources/harness.js
In some versions of Safari stringifies the object rather than using the word "function".  This PR fixes it to catch for such cases.
=> Fix constructor test function

custom-tests.json, static/resources/harness.js
This PR adds and updates a number of custom tests:
- Add custom tests for PeriodicWave and PluginArray APIs
- Improve constructor test
- Add custom test for Plugin API
- Add custom test for TimeRanges API
- Add custom test for XPathResult
- Add custom test for StyleSheetList
- Add custom test for WebSocket API
- Explicitly use WebGL1 or WebGL2 for extensions that need it
=> Add and improve custom tests

custom-tests.json
SVGAnimatedPoints is a mixin, which we can't create an instance for.
=> Fix the custom test for SVGPointList

selenium.js
This doesn't change anything, but makes it obvious at a glance that we
don't depend on the actual BCD data here.
=> Trim the selenium.js BCD dependency to just browsers

custom-tests.json
These are tests where `'property' in object` checks could be simplified.
The `CacheStorage` test additionally did unnecessary branching on the
context, where the instances is `self.caches` regardless.
=> Simplify some custom tests

build.js
This results in 812 new tests being generated for the interfaces and
their members.
The comment is true, but many event interfaces *are* exposed and it's
worth having the tests for them. Care is still needed while using the
results, but that could be added to update-bcd.js.
This reverts a change from https://github.com/foolip/mdn-bcd-collector/pull/735.
=> Generate tests for event interfaces

build.js
This removes the following incorrecly generated tests:
api.AudioParamMap.clear
api.AudioParamMap.delete
api.AudioParamMap.set
api.BluetoothManufacturerDataMap.clear
api.BluetoothManufacturerDataMap.delete
api.BluetoothManufacturerDataMap.set
api.BluetoothServiceDataMap.clear
api.BluetoothServiceDataMap.delete
api.BluetoothServiceDataMap.set
api.EventCounts.clear
api.EventCounts.delete
api.EventCounts.set
api.GPUAdapterFeatures.add
api.GPUAdapterFeatures.clear
api.GPUAdapterFeatures.delete
api.KeyboardLayoutMap.clear
api.KeyboardLayoutMap.delete
api.KeyboardLayoutMap.set
api.MIDIInputMap.clear
api.MIDIInputMap.delete
api.MIDIInputMap.set
api.MIDIOutputMap.clear
api.MIDIOutputMap.delete
api.MIDIOutputMap.set
api.RTCStatsReport.clear
api.RTCStatsReport.delete
api.RTCStatsReport.set …
=> Avoid generating extra tests for readonly setlike/maplike

custom-idl/IndexedDB.idl, custom-idl/css-animations.idl, custom-idl/css-transitions.idl, custom-idl/cssom.idl, custom-idl/encrypted-media.idl, custom-idl/geometry.idl, custom-idl/mediacapture-streams.idl, custom-idl/speech-api.idl, custom-idl/uievents.idl, custom-idl/webaudio.idl, custom-idl/webrtc.idl
This was a bit inconsistent, with some things using partial interface
Window and others using interfaces. Use interfaces consistently where
it's a matter of an alias, more like what we've been doing for members.
This also makes it possible to test the constructors separately.
=> Expand on custom prefixed interface tests

package-lock.json, package.json
This results in these new tests:
api.DataCue
api.DataCue.DataCue
api.DataCue.type
api.DataCue.value
api.GPUDevice.createComputePipelineAsync
api.GPUDevice.createRenderPipelineAsync
api.GPUDevice.queue
Some api.GPUDevice.* tests are also removed.
=> Update webref IDL

views/index.ejs
Apparently IE 5.5 is no longer supported...ah well!  This is a quickie to update the compat table on the front.﻿
=> IE 5.5 no longer supported

build.js, custom-idl/file-system-api.idl, custom-idl/html.idl, package-lock.json, package.json, unittest/unit/build.js
- Drop validation now done by webref tests
- Simplify the buildIDL test to a very basic smoke test.
- webref is still needed for CSS definitions, so is left in for now.
This also reverts the accidental `undefinedFunction` from #675.
=> Get spec IDL from the new @webref/idl package

custom-tests.json
innerHTML is supported earlier than innerText.
Fixes https://github.com/foolip/mdn-bcd-collector/issues/961.
=> Use innerHTML instead of innerText to create a Text instance

custom-tests.json
The tests for AudioParam/AudioParamMap/ScriptProcessorNode return all
false because reusableInstances.audioContext isn't created.
Add the missing dependency and fix the .createScriptProcessor() call.
The AudioParamMap test would be work to fix, so remove it to get
prototype tests for now.
=> Fix some custom Web Audio API tests

custom-tests.json
MediaSettingsRange is a dictionary so no tests end up being generated
based on this code.
=> Remove MediaSettingsRange (dictionary) custom test

package-lock.json, package.json
The only change in generated tests is that EncodedAudioChunk tests are
run in workers too.
=> Bump @webref/idl and webidl2

app.js, unittest/app/app.js
This isn't documented in DESIGN.md and isn't useful at all.
=> Send no response for /api/results

DESIGN.md, app.js, results.js, unittest/app/app.js, unittest/unit/results.js
This is in preparation for exposing the results as a URL available to
another client (Selenium). It should be difficult to store arbitrary
data in the service to make it unattractive for abuse.
This also modifies the results format, notably dropping the code.
=> Validate the payloads sent to /api/results

static/unittest/index.html, views/layout.ejs
Large comments before <meta charset="utf-8"> risks breaking it:
https://hsivonen.fi/label-utf-8/
=> Remove copyright notices from HTML files

selenium.js
When running this script timeouts are pretty common. Especially the 5s
timeout seems problematic, since the main thread might be blocked
running the tests at that point.
=> Increase Selenium timeouts to 30s

custom-tests.json
This appears to be the cause of Edge 12-18 not working. This
unfortunately loses some good coverage, which perhaps should be brought
back when running tests manually but skipped in automation.
=> Avoid calling getUserMedia() in custom tests

app.js, tests.js, unittest/unit/tests.js, views/tests.ejs
This makes it easier to test, and it's changed to be more strict than it
was before.
=> Move ignore (test filtering) logic into getTests

custom-tests.json, selenium.js
This reverts https://github.com/foolip/mdn-bcd-collector/pull/1008.
=> Restore getUserMedia() for custom tests and skip them in Edge 12-18

build.js, unittest/unit/build.js, unittest/unit/tests.js
This is only used internally in build.js and not when serving, so just
remove it from tests.json.
This reduces the size of tests.json by ~8%.
=> Remove the test category from tests.json

build.js, tests.js, unittest/unit/build.js, unittest/unit/tests.js
This reduces the size of tests.json by ~14%, but doesn't change the
output of /tests/ at all, due to the old "API" being left with a TODO
in getTests. Simplifying that would potentially be a win for the time it
takes to actually run the tests.
=> Simplify code and resources in tests.json

custom-tests.json
AudioBufferSourceNode is as of as the Web Audio API itself, and will
do for testing if AudioScheduledSourceNode members were supported.
=> Use a AudioBufferSourceNode instance to test AudioScheduledSourceNode

custom-idl/webaudio.idl
No longer needed after https://github.com/mdn/browser-compat-data/pull/9599.
=> Remove custom tests around AudioScheduledSourceNode

unittest/unit/update-bcd.js, update-bcd.js
Prefixes and alernative names will be handled with a different approach,
with distinct tests in mdn-bcd-collector, mapping those to a subset of
the support statements in BCD. In other words, it will happen at a layer
up from most of this code, not requiring any changes to getSupportMap or
getSupportMatrix.
Because mdn-bcd-results doesn't contain any prefix information, this doesn't
change what edits are made when using the results from v2.0.1.
=> Remove unused support for update-bcd to updated prefixed entries

package.json, unittest/unit/update-bcd.js, update-bcd.js
The previous logic for finding a `simpleStatement` considered anything
with a `version_removed` to be non-simple, going down the code path of
adding entries unless an identical one already existed.
Instead, limit this case to when there were no existing statements, in
which case there's no merging of entries to worry about.
Defer dealing with multiple existing statements or multiple inferred
statements beyond the simple case of no existing statements.
The resulting edits suggest differ by quite a lot from the previous
state, overall updating fewer files.
Fixes https://github.com/foolip/mdn-bcd-collector/issues/1068.
https://github.com/foolip/mdn-bcd-collector/issues/875 is the plan for
catching differences in the data which cannot yet be fixed
automatically.
=> Make update-bcd more conservative about updating existing data

build.js, custom-idl/dom.idl, custom-idl/html.idl, unittest/unit/build.js
A custom validation rule for this was removed in
https://github.com/foolip/mdn-bcd-collector/pull/959, but what remains
is insufficient to catch accidentally duplicated custom IDL.
Fix the duplicates that had crept in since then.
=> Check for all duplicates (not just operations) in mergeMembers

build.js
The `code` parameter is never an array at these call sites.
There are no changes to tests.json as a result of this.
=> Remove '&&' combinator in compileTest calls where not needed

build.js, unittest/unit/build.js, unittest/unit/tests.js
Instead generate both forms for the document.body.style tests where
appropriate, to deal with odd -apple- and -epub-prefixed properties.
Fixes https://github.com/foolip/mdn-bcd-collector/issues/12.
=> Stop using CSS.supports for CSS property tests

custom-tests.json
No fetch happens since load() isn't called, but this comes up when
looking for external URLs, so just replace it with a relative URL that
would work if actually fetched.
=> Avoid external URL in FontFace source

custom-tests.json
Using "unknown" creates an Element instance on Edge 18 and possibly
other browsers. Instead use <title>, since it's as old as SVG itself,
and SVGTitleElement has no members of its own:
https://www.w3.org/TR/SVG10/struct.html#DescriptionAndTitleElements
https://svgwg.org/svg2-draft/struct.html#DescriptionAndTitleElements
Aside: That's impressive ID stability over the decades.
=> Test SVGElement using a <title> element instance

custom-tests.json
This avoid the potential problem with workers being supported but the
WorkerNavigator interface itself just not being exposed.
Also drop the window. prefix in some other tests, since it was
inconsistently used and skipping it makes Window+Worker code consistent.
=> Use navigator as the WorkerNavigator instance

custom-tests.json
This PR adds a custom test for the WebGLVertexArrayObjectOES API.  This was created in response to https://github.com/mdn/browser-compat-data/pull/10715.
=> Add custom test for WebGLVertexArrayObjectOES API

selenium.js
BrowserStack doesn't support Safari x.0 versions since Safari 10.  This PR updates the Selenium script to ensure that Safari 14.0 is run on SauceLabs instead.﻿
=> Selenium: don't try to test Safari 14.0 in BrowserStack

custom-tests.json
This PR fixes an issue with the custom test for the `ProcessingInstruction` API.  When I initially wrote the custom test, I thought that it had to say `xml`, when in fact, it was the exact opposite.
=> Fix custom test for ProcessingInstruction API

custom-tests.json
Testing onerror on Worker.prototype isn't enough because it goes back to
before when attributes were consistently exposed on the prototypes.
Reusable instances are used to avoid spawning lots of workers.
=> Add reusable instances of Worker and SharedWorker

custom-tests.json
From my recent testing, I've found that BrowserStack doesn't have a camera setup on their VMs.  In turn, this is causing our tests to throw an error, due to being unable to find a device befitting of those constraints.  This PR reworks the related custom tests to only grab the microphone (which BrowserStack does have) for most tests, and the video only when needed.﻿
=> Improve MediaStream tests for camera-less devices

package-lock.json, package.json
Notable changes:
https://github.com/foolip/mdn-bcd-collector/pull/1194
https://github.com/foolip/mdn-bcd-collector/pull/1195
https://github.com/foolip/mdn-bcd-collector/pull/1198
https://github.com/foolip/mdn-bcd-collector/pull/1203
Added tests:
api.GPUSupportedLimits
api.GPUSupportedLimits.maxBindGroups
api.GPUSupportedLimits.maxDynamicStorageBuffersPerPipelineLayout
api.GPUSupportedLimits.maxDynamicUniformBuffersPerPipelineLayout
api.GPUSupportedLimits.maxSampledTexturesPerShaderStage
api.GPUSupportedLimits.maxSamplersPerShaderStage
api.GPUSupportedLimits.maxStorageBufferBindingSize
api.GPUSupportedLimits.maxStorageBuffersPerShaderStage
api.GPUSupportedLimits.maxStorageTexturesPerShaderStage
api.GPUSupportedLimits.maxTextureArrayLayers
api.GPUSupportedLimits.maxTextureDimension1D …
=> Release 3.1.5

custom-tests.json
The exception type was supported long before its constructor in some
browsers, so this is necessary to get the right data.
=> Get a DOMException instance from a thrown exception

custom-tests.json
This updates the custom test for the ProcessingInstruction API, using the example from the MDN documentation, particularly to increase compatibility with Internet Explorer.  The original test wouldn't function in IE, throwing a "NotSupportedError".
=> Update custom test for ProcessingInstruction

static/resources/harness.js, static/resources/style.css, views/tests.ejs
When running the tests, we have the code configured to add the DOM for the submit buttons once we've completed the tests.  However, this causes the elements to move down on the page, which has caused me to sometimes hit one of the export buttons when trying to expand the collapsed code.  This PR is intended to fix this issue by always keeping the buttons in the DOM, disabled by default, and then enable them when the tests are done.
Tested functional in: Chrome 15 + 91, Safari 4 + 14, Opera 12.1, Firefox 4 + 89, IE 6 + 11
=> Always show form buttons, but disable by default

custom-tests.json
Event.createEvent() is not a thing.
As a drive-by, also update the strings used for DOMError and Even
constructors to match the argument names.
=> Fix the fallback for creating an Event instance

custom-tests.json
This avoids `window.performance` in workers and
`var performance = perfomance` due to
`<%api.Performance:performance%>` used previously.
=> Fix Peformance* custom tests

custom-tests.json
- Hoist the `var instance` since it's already hoisted by JavaScript
- Use document.createElement('b') to get an `HTMLElement`, not 'p'
since that gets an `HTMLParagraphElement`. The difference probably
doesn't matter in any of our tests, but anyway...
=> Tweak some custom tests for consistency

custom-tests.json
All of window.*bar are very old, but this one gets the most hits on
Google and appears in old documentation like this:
https://www.oreilly.com/library/view/pure-javascript/0672315475/0672315475_ch07lev2sec592.html
=> Use window.toolbar as a BarProp instance

custom-tests.json
It doesn't matter, but it's just as well to use a direct instance of the
interface under test when it's possible.
=> Use <b> as a HTMLElement instance (not HTMLUnknownElement)

selenium.js, static/resources/harness.js
This PR performs a number of updates to the Selenium script to resolve some issues caused by some new custom tests, along with existing tests, due to permissions requirements.  This PR also performs a few other little updates to make the script a little nicer, including the following:
- Increase test timeout
- Turn the browser-specific ignores into arrays rather than strings
- Remove logic to remap Safari 6.1
- Allow mic, camera, geolocation, and notifications for Chrome, Edge and Firefox
- Simplify code to ignore the Safari x.0 versions on BrowserStack
- Increase verbosity of tests and add more comments
- Encode the commas in URLs for EdgeHTML versions of Edge (due to some odd issues)
- Add a command line argument to reverse the browser's version order in testing (oldest-to-newest)
- …
=> Selenium script updates

README.md, secrets.sample.json, selenium.js
This PR provides even more Selenium script updates for legibility, convenience, and simplicity.  Some legibility/simplicity updates include the following:
- Create getBrowsersToTest()
- Create getOsesToTest()
- Move functions
- Update documentation regarding Selenium script
A big update involves the handling of the Selenium URLs as well.  This refactors the Selenium URLs to take an object containing the user's credentials, which then fills a pre-programmed URL for the service.  This allows a user to simply define the username and API key for BrowserStack or SauceLabs and let the script handle the rest.  This will also make it easier for #1222 to tap into the API keys right from `secrets.json`.
This refactoring will not conflict with the existing method of defining Selenium remotes.  Both …
=> More Selenium script updates

results.js, unittest/unit/results.js
This PR increases the verbosity of the errors thrown by the results parser (`results.js`).  This will help us get to the bottom of any issues we're experiencing a little easier.
=> Increase the verbosity of errors in results parsing

static/resources/harness.js
This PR fixes a small bug with the error processing of the error thrown by old Firefox versions when attempting to create a WebKitAnimationEvent.
=> Fix Firefox collection regarding new WebKitAnimationEvent test

static/resources/harness.js, views/tests.ejs
This PR adds IDs for the export buttons.  This fixes a compatibility issue with early Firefox versions, as well as allows for forcing a click of the buttons.
=> Add IDs for export buttons

build.js, unittest/unit/build.js
This PR updates the custom tests' importing mechanic to rename the variables in assignments without the `var` keyword present, such as in the case of the `Element` API.  This fixes custom tests like the `DOMRectList` API.﻿
=> Custom tests: replace variable assignments as well

selenium.js
This PR should help bypass some of the OS-level permissions issues﻿we've been dealing with, so that we can get all the results for Firefox easily.
=> Enable fake media stream for Firefox in Selenium script

ua-parser.js, unittest/unit/ua-parser.js
A while back, I accidentally merged a PR where I ran the collector on Chrome iOS.  At first, I didn't notice the odd results surrounding Chrome 91, but then when I looked closely, I realized it was due to the merge of a Chrome iOS result.
This PR updates the UA parser to treat iOS similar to Android, adding a suffix to the browser ID and name to indicate it's an iOS browser.  This will make Chrome iOS (and any other browsers on iOS that aren't Safari itself) register as not a part of BCD, instead of treating it as Chrome Desktop (as it is now) or merging the results into Safari iOS (since some browsers have varying API support).﻿
=> Update UA parser to better handle iOS browsers

custom-tests.json
This PR adds custom tests for the `WritableStreamDefaultController` and `WritableStreamDefaultWriter` APIs.  Since neither seem to be exposed as their own interfaces, this will let us collect results properly.﻿
=> Add custom tests for WritableStreamDefaultController/Writer

custom-js.json
As it turns out, these appear on Error instances and not on the
prototype, just like the stack property.
These will need custom tests, drop generated tests.
=> Remove tests for columnNumber/fileName/lineNumber

custom-js.json
This is a Firefox-only feature, but this feature detection doesn't work.
Going by the description on MDN, it's probably a property that code can
only set, and FireFox DevTools might look for that property:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/displayName
Just don't test it for now.
=> Remove Function.prototype.displayName test

package-lock.json
It's required by npm 7.
Now that dependabot also supports it, I guess it's time to upgrade 👀
=> Upgrade lockfile version to 2

selenium.js
This is a workaround for #1281 until we can figure out a better solution.  This PR disables the user media APIs for Firefox 34-52 to prevent the Selenium script freezing during these Firefox versions.
=> Ignore user media tests on Firefox 34-52

custom-tests.json, package-lock.json
This is apparently a reserved keyword in strict mode and is breaking
these tests.
=> Fix variable names in custom tests to avoid "interface"

custom-tests.json
This PR fixes the tests for the WritableStreamDefaultController and WritableStreamDefaultWriter interfaces, so that they check for support of WritableStream first.﻿
=> Fix tests for WritableStreamDefaultController/Writer

unittest/unit/update-bcd.js, update-bcd.js
These objects only had a single property, making the code around it more
convoluted for no good, and harder to debug.
=> Simplify getSupportMap to use bare values, not {result: ...}

selenium.js
This PR fixes the preferences for Firefox so that we can properly collect results on macOS.﻿
=> Correct preference for fake Firefox media stream

update-bcd.js
It's not used for anything, so just deal with true/false/null results.
=> Simplify getSupportMap by ignoring URL

custom-tests.json
This PR improves the WebSocket API custom test in two ways:
1) Checks for WebSocket support before attempting to construct one
2) Checks for support under the `Moz` prefix as well﻿
=> Improve test for WebSocket API

custom-tests.json
Apparently, the resolver argument was required in earlier versions of Firefox (57 and below).  This PR corrects the test to work with these older Firefox versions.
=> Fix test for XPathResult

custom-tests.json
This PR fixes the Notification API custom test, by checking to see if the Notification API is defined first before attempting to construct a Notification instance.﻿
=> Fix custom test for Notification API

custom-tests.yaml
For XMLHttpRequestEventTarget we could use either XMLHttpRequest or
XMLHttpRequestUpload and it's possible some event was first supported
for upload, but checking for support in both would be more involved.
=> Add instances for XMLHttpRequestEventTarget and XMLHttpRequestUpload

custom-tests.yaml, static/resources/harness.js, static/resources/serviceworker.js, static/resources/sharedworker.js, static/resources/worker.js
- Speed up CryptoKey tests with reusable instance
- Re-disable BatteryManager tests
- Ensure workers have access to reusable instances
=> Custom test updates

static/resources/harness.js
This PR fixes a bug where older versions of Chrome and Safari (and possibly Firefox too) try to send the results to `example.org` instead of our own website.﻿
=> Fix odd bug with older browsers trying to post results to example.org

custom-tests.yaml
This PR fixes the `cryptoKey` instance to ensure `subtleCrypto` exists before attempting to generate a key.﻿
=> Fix cryptoKey instance

package-lock.json, package.json
This release includes a critical bug fix that causes issues with submitting results in Chrome ≤20 and Safari ≤6.  Additionally, this includes some improvements to the debug mode logs, and a fix for the `cryptoKey` instance.﻿
=> Release 3.2.6

custom-tests.yaml
This is a continuation from #1392 which fixes further issues I've found with the page links, including the export buttons.  The changes in #1392 fix an issue in some older Firefox releases as well, so there's no need to revert those changes.﻿
=> Revert documentURI after testing api.Document.documentURI.readonly

package-lock.json, package.json
This release properly fixes the bug in Chrome ≤20 / Safari ≤6 attempting to post results and navigate to `https://example.org`.﻿
=> Release 3.2.7

package-lock.json, package.json
This release includes two bug fixes (one minor, one major):
- Check if `crypto` is defined before attempting to create `cryptoKey` instance (minor)
- Use `location.protocol` and `location.host` instead of `location.origin` to provide support for older browsers (major)﻿
=> Release 3.2.8

static/resources/harness.js
This PR updates `bcd.testConstructor()` to account for Presto-based Opera's unsupported error message.﻿
=> Account for Opera Presto error

custom-tests.yaml, selenium.js
This PR is a follow-up to the event interface tests, fixing a few bugs.
- During creation, we now catch when `document.createEvent` throws a `NotSupportedError` error, and we treat that as "no support".﻿
- If `SecurityPolicyViolationEvent` is undefined, don't attempt to construct it and instead return false.
- Edge 15 reloads the page when a `SecurityPolicyViolationEvent` is created; ignore it in Selenium.
=> Updates for event custom tests

custom-tests.yaml
- Fix test for RTCPeerConnection for older browsers
- Use bcd.testConstructor to check if the constructor is one
=> Fix test for RTCPeerConnection

custom-tests.yaml
Addresses https://github.com/mdn/browser-compat-data/pull/12033.﻿
=> Use performance.getEntries() to get PerformanceEntry instance

custom-tests.yaml
This PR fixes the comment regarding the constructor for RTCPeerConnection by using `/* */` for comments rather than `//`.  This fixes the conflict with Prettier formatting.﻿
=> Fix the comment for RTCPeerConnection

custom-tests.yaml
This PR fixes a results bug in earlier Safari versions, where `window.crypto` exists and is explicitly being defined as `undefined` (see https://github.com/mdn/browser-compat-data/pull/12152#discussion_r702260957).﻿
=> Fix Safari bug for window.crypto

custom-tests.yaml
This PR updates the custom test for the `ImageData` API.  Initially the test relied only on a canvas rendering context, but this API also has a constructor.  Now, this test attempts the constructor first, and if the constructor doesn't work, fallback to using the canvas rendering context.﻿
=> Update custom test for ImageData

custom-tests.yaml
First checking `'crypto' in window` is redundant.
=> Simplify window.crypto custom test

custom-tests.yaml
This PR fixes the custom test for the RTCPeerConnection API.  Apparently in these earlier versions, it was actually that the non-prefixed version was unintentionally exposed and wasn't a valid constructor.  The test now attempts to use the prefixed variant first to resolve this issue.﻿
=> Fix custom test for RTCPeerConnection

custom-tests.yaml
This PR removes the custom test  for `api.Document.documentURI.readonly`.  Correlates with the subsequent removal in BCD (https://github.com/mdn/browser-compat-data/pull/12276).﻿
=> Remove custom test for api.Document.documentURI.readonly

custom-tests.yaml
This needs a custom test because the interface has
[LegacyNoInterfaceObject] in Chromium.
=> Use document.fonts or self.fonts as FontFaceSet instance

static/resources/harness.js
The tests for Worker were always sent here, which is right often enough
that nobody noticed until now. However, when there are no Worker tests,
it breaks.
This doesn't change the generated tests, but it will change which tests
are actually run, and so might have a big impact on the results.
Fixes https://github.com/foolip/mdn-bcd-collector/issues/1478.
=> Send the right tests to SharedWorker and ServiceWorker

custom-tests.yaml
Even with this change the test doesn't work as far back as FetchEvent is
probably supported, but at least it now works for current browsers.
=> Add required request parameter to FetchEvent constructor

.github/workflows/push.yml
This PR updates the `push` workflow to automatically tag new releases as needed.
=> Automatically tag new releases

.github/workflows/push.yml
Forgot to attach the GitHub token to the auto-tag action beforehand, whoops!  This is a quick fix to attach it.
=> Attach GitHub token to auto-tag action

update-bcd.js
This fixes an issue where the call to `yargs` is looking for the `browsers` variable, but it isn't initialized yet.
=> Fix import order in update-bcd script

custom-tests.yaml
This is required for accurate detection of the earliest support.
=> Use WebKitMutationObserver to create a MutationObserver instance

custom-tests.yaml
These tests will return true even if the options are completely ignored.
=> Remove insufficient tests for document.createElement() options

.github/workflows/push.yml
This PR replaces the non-functional `max-parallel` parameter with `concurrency`, which is supposed to ensure that only one deployment job runs at a time.  This will cancel any in-progress deployment to ensure that we'll always deploy the latest version.
=> Limit deploy action to only run one at a time

app.js
This PR fixes the bug addressed in #1049.  After reading the documentation for Express, it turns out that I was misusing `app.locals`.  `app.locals` is for the lifetime of the _server,_ which is fitting for variables like the app's version.  For per-request variables, however, we want to use `res.locals` instead.﻿
=> Keep UA parse results specific to the request, not the app

custom-tests.yaml
This PR fixes the test for the `ImageCapture` API.  `getUserMedia` returns a media _stream,_ rather than a media stream's track, but this was not accounted for.  This PR fixes the custom test by ensuring we're grabbing the video track.﻿
=> Fix test for ImageCapture interface

custom-tests.yaml
This is to go along with its renaming in BCD.
=> Rename api.BaseAudioContext.decodeAudioData.promise_syntax -> returns_promise

custom-tests.yaml
This PR updates the tests for the `TextDecoder` and `TextEncoder` APIs.  Both of these need to be constructed before they can be used, so this﻿ PR checks whether they're defined first.
=> Update tests for TextDecoder/TextEncoder

custom-tests.yaml
This PR updates the `IIRFilter` and `MediaStreamAudioDestinationNode` tests to return false when the `AudioContext` features it depends on are not available.﻿
=> Update IIRFilter + MediaStreamAudioDestinationNode custom tests

static/resources/harness.js
This PR adds two pieces of code to prevent the tests from starting multiple times:
- Clears the timeout on waiting for resources to load if the resources failed to load
- If `startTests()` is called multiple times, log to the console and return
This provides critical performance improvements for old browsers.﻿
=> Prevent tests from starting twice

selenium.js
This PR is a quick update to simplify the import for Listr (since it now has ESM bindings) and switch to the preferred subtask style.﻿
=> Simplify Listr calls in selenium.js

static/resources/harness.js, static/resources/serviceworker.js, static/resources/sharedworker.js, static/resources/worker.js, views/index.ejs, views/tests.ejs
This PR updates our code to only load JSON3 when it's needed, in two ways:
- Only load JSON3 _after_ all the tests; it's not needed for worker tests at all since workers were added after JSON support
- Check if we need to load the polyfill in the first place; if the browser has the JSON support we need, don't load the script
=> Load JSON3 polyfill only when needed

ua-parser.js, unittest/unit/ua-parser.js
Looks like because we're stripping the patch version from the version number, we're accidentally mapping 4.4.3 to 4.4 -- see https://github.com/foolip/mdn-bcd-results/pull/2719.﻿
=> Handle Android WebView 4.4.3 in ua-parser

static/resources/harness.js
This PR simplifies the code we use to check if an exposure was run twice, by completely removing it.  Instead, we ensure that the callback can only be called once.﻿
=> Simplify code to check for double-run of test exposures

selenium.js
Forgot to switch the import from `chalk` to `chalk-literal` here, whoops!
This also partially reverts #1697; apparently Listr's a bit buggy with this new style, so annoying.  Old style worked just fine.  😛﻿
=> Switch chalk -> chalk-literal; revert to old Listr style

build.js, unittest/unit/build.js
As it turns out, both `maplike` and `setlike` interfaces have an `@@iterator` symbol upon them, as stated in the [WebIDL spec](https://webidl.spec.whatwg.org/#es-iterators).  This PR ensures we are creating these symbols.﻿
=> Add @@iterator symbol on maplike and setlike interfaces

custom-tests.yaml
This PR updates the custom test for the Attr API to use `Element.attributes` as a fallback, particularly for older browsers like IE.  Fixes #955.﻿
=> Update Attr API custom test

views/tests.ejs
Now that JSON3 is no longer imported, I think it's safe to remove this TODO.﻿
=> Remove TODO comment about #407

find-missing-features.js
This PR updates the wording for the `direction` argument of the `find-missing-features` script for better clarity.﻿
=> Update wording for find-missing-features' direction argument

custom-idl/mediacapture-transform.idl
This was included in @webref/idl 2.12.0:
https://github.com/w3c/webref/pull/450
=> Remove MediaStreamTrackProcessor custom IDL

package-lock.json, package.json, release.js
Due to the issues with `nodegit` and its inhability to compile on anything newer than NodeJS v14, I think it's time for a switch.  There isn't really any good library out there, so I figure parsing CLI output would be much simpler and reasonable enough.
This PR fixes #1751.﻿
=> Remove NodeGit as dependency; use raw git commands in release script

exporter.js
This fixes a problem where the "dev version" warning will not show up in results PR bodies.﻿
=> Make sure to include collector version in exporter.getReportMeta

build.js, unittest/unit/build.js
This PR adds support for [wildcard exposure sets](https://webidl.spec.whatwg.org/#ref-for-dfn-xattr-wildcard%E2%91%A0).  While this feature is rarely used (currently only in a WICG draft spec, https://wicg.github.io/compression/#compression-stream), it was included in Webref/idl v3, which is blocking #1747.  This maps the wildcard to the four main exposure sets (window, worker, shared worker, and service worker).
Additionally, this renames the "globals" variable within `getExposureSet()` to `exposure` for better naming.
=> Add support for wildcard exposures

build.js
This PR removes code that generates tests for constants.  We are filtering out all constants in earlier code, so this section is never reached.
=> Remove unreachable code in build.js

package-lock.json, package.json, unittest/puppeteer/harness.js
This PR fixes the codecov reporting coming from Puppeteer, so that code coverage is included in `c8`/`istanbul`.  Fixes #1789.
=> Fix Puppeteer codecov reporting

release.js
This PR updates the changed test lists by consolidating the lists so that all the children won't be listed if the parent has been modified (i.e. if 'api.AbortController' was added, 'api.AbortController.someProperty' won't be included in the list)
=> Release script: simplify test list

find-missing-results.js
This PR fixes the find-missing-results script.  Apparently, when performing `'15' > '4'`, the strings are not converted to numbers during comparison, but rather compared lexicographically.  This PR fixes that by replacing one of the sides of the comparison with an integer, so that IE 10 and 11 are included in the list, as well as Safari 10 or higher.
Additionally, this removes the clause to exclude Safari 6.1, since BCD no longer has 6.1 in its data.
=> Fix find-missing-results

build.js, custom-css.json, static/resources/harness.js, unittest/unit/build.js
This also adds a lot of the more easily found values that either differ between {Chrome, Firefox, Safari} _or_ where entries already exist in BCD for them.
This almost certainly isn't quite what we want, but it's a starting point. Notably this produces significant changes to BCD data, as (unsurprisingly) plenty of this data is outdated.
Fixes #705, based on @foolip's earlier experience with #1221.
=> Add the ability to test CSS property values to custom-css.json

custom-tests.yaml
This PR adds custom tests for the `toString` method of the `HTMLAnchorElement`, `HTMLAreaElement`, and `WorkerLocation` interfaces.  This is a sister PR to #1716, which updates `build.js` to include these members.﻿
=> Add custom tests for HTML[Anchor/Area]Element/WorkerLocation toString

build.js, unittest/unit/build.js
This PR updates the build script to add `toString` tests for any _named_ attributes with the `stringifier` special attribute.  This case can be found in the `HTMLHyperlinkElementUtils` mixin and `WorkerLocation`﻿interface.
Fixes #1057.
=> Generate toString tests for named stringifiers in IDL

ua-parser.js
This bug was fixed upstream, so our mitigation is no longer needed.
=> Remove mitigation of Firefox 3.6.17 UA parsing bug

unittest/unit/bcd.test.js, unittest/unit/find-missing-features.js, unittest/unit/update-bcd.js, update-bcd.js
This PR updates the `update-bcd` to ensure that the script won't replace a version with `false` if the version number is newer than the data we have.  For example, if BCD's version is set to "17", but we only have results up to "16" and "false" is inferred, BCD will remain set to "17".  Fixes #659.
=> Don't set BCD to false if BCD has version number greater than our data

update-bcd.js
This PR fixes #1834 by handling "preview" as a version in `update-bcd`.
=> Handle "preview" in update-bcd

static/resources/harness.js
This PR tweaks the regex used to get which reusable instances were reused in hte custom test.  This should fix the code display in `api.CSSConditionRule`.
=> Fix regex to catch reusableInstances in tests

app.js
This PR reverses the preference of staging vs. production when `NODE_ENV` is production.  Currently, the website is only in production mode when the `GAE_VERSION` is set to `production`.  However, this essentially means that with our current code, we can only launch a production deployment on Google App Engine.  This PR reverses the preference, so that production is the default when `NODE_ENV` is `production`. ~~, and staging deployment is on when `GAE_VERSION` is `staging`.~~
~~@foolip, can you confirm the staging version has `GAE_VERSION=staging`?~~
Edit: since the staging version was removed from GAE, this PR has now been adjusted so that it is only based upon `NODE_ENV` and has no logic for `GAE_VERSION`.
=> Set to production by default if NODE_ENV = production

release.js
This PR uses the `npm version` command as inspired by BCD's release process to bump the version number, rather than manually.
=> Use npm version to bump version in release script

selenium.js
This PR switches the `-s` flag that forces Selenium jobs to run sequentially with a `-j#` flag to specify the number of concurrent jobs, much like `make`'s flag.
=> Allow for defining custom number for concurrent Selenium jobs

custom-js.json
These were identified using the find-missing-features script.
All of the added tests pass in either Chrome 100 or Firefox Nightly,
some in both. javascript.builtins.WebAssembly.Tag.type notably fails in
Chrome, even though javascript.builtins.WebAssembly.Tag passes. This
seems like a legit missing feature.
=> Add missing JS builtins

app.js, exporter.js, unittest/unit/exporter.js
This PR updates the app to use `git describe` to create a version number for the development version.
=> Use 'git describe' to generate version number for dev version

app.js, app.yaml, storage.js, unittest/unit/storage.js
The main purpose of this is to stop using GAE_VERSION, to allow it to be
anything and make it easy to deploy multiple versions in parallel.
Use the app version as a path prefix in the single bucket to clearly
separate data from different versions, and remove the need for a staging
bucket. Collisions were already unlikely, but sessions for all
deployments would still be mixed in a single bucket.
While changing things, also add /sessions/ to the path of temporary
results storage, since /files/ is already used for exported reports.
=> Use a single storage bucket with app version as path prefix

custom-css.json, custom-tests.yaml
The way this works is confusing, an issue was filed:
https://github.com/foolip/mdn-bcd-collector/issues/1944
=> Restore the css.properties.custom-property custom test

selenium.js
This PR performs a few changes to the Selenium script:
- Fix crash with SauceLabs
- Add shorthands to arguments
- Set test name appropriately on SauceLabs
- Handle SauceLabs' lack of remapping W3C capabilities (for now)
- Use includes() vs. startsWith()
=> Update Selenium script

update-bcd.js
This PR fixes `update-bcd` to replace any data in BCD marked as `preview` if our data suggests a version number.
=> Replace "preview" in BCD if collector has version number

.github/workflows/pull_request.yml
Tests on Windows commonly crash due to timeouts.  This PR removes Windows from the test matrix.
=> Don't run tests on Windows

static/resources/harness.js
This PR fixes `testConstructor()` to catch an additional error message returned by constructors, specifically one that Safari now throws when attempting to construct a `ByteLengthQueuingStrategy`.  Fixes the bug found in https://github.com/mdn/browser-compat-data/pull/15975.﻿
=> Update testConstructor() to catch Safari error message

static/resources/harness.js
This PR updates the `stringIncludes()` function within `harness.js` to allow for arrays as a search parameter.  This helps us simplify our function calls.﻿
=> Allow stringIncludes() search to be an array

add-new-bcd.js, app.js, build.js, custom-idl/index.js, exporter.js, find-missing-features.js, scripts.js, selenium.js, storage.js, unittest/puppeteer/harness.js, update-bcd.js
This PR prefixes all imports for NodeJS built-ins with `node:` to clarify imports better.
=> Prefix NodeJS built-in imports with `node:`

custom-tests.yaml
This contains a new line within a JS string, which is syntactically invalid, and results in every browser giving null for this test.
=> Fix api.CSSKeyframesRule, which is currently invalid JS

CHANGELOG.md, release.js
This PR updates our changelog-creating functions in `release.js` to link to the pull requests in the changelog, since it appears that GitHub does not do this for us in CHANGELOG.md.
=> Link to pull requests in changelog

update-bcd.js
This PR is a follow-up to https://github.com/mdn/browser-compat-data/pull/16475 to remove the mitigation needed when mirroring a browser that is also mirroring another.
=> Remove Object.assign() to mitigate mirroring changing upstream

build.js
This PR allows the IDL to contain static members that use the same name as non-static members, as per the [WebIDL standard](https://webidl.spec.whatwg.org/\#idl-operations:\~:text\=Note%3A%20The%20identifier%20of%20a%20static%20operation%20can%20be%20the%20same%20as%20the%20identifier%20of%20a%20regular%20operation%20defined%20on%20the%20same%20interface.).  This is required to land #2049.
Note: while this logic can theoretically be simplified to `member.name + member.special`, I wanted to limit the scope to just what's allowed in the spec.
=> Allow for static members of the same name as non-static members

build.js
This PR is a follow-up to #2054.  Instead of simply ignoring static members with the same name as non-static members, this PR adjusts the logic to ensure they aren't included in the merged member output at all.  Closes #2061.
=> Don't include static members with the same name as non-static members

app.js, views/layout.ejs
This PR adds the BCD version to the message indicating that the browser version isn't in BCD.  This is helpful to inform users that the browser version may not be in BCD simply because the current collector version does not have an updated BCD version.
=> Show BCD version when browser version isn't in BCD

find-missing-results.ts, package.json, update-bcd.ts
This PR converts the `find-missing-results` script to TypeScript.
=> Convert find-missing-results to TypeScript

custom-css.json
These are all the values listed in the spec:
https://drafts.csswg.org/css-break/#break-between
https://drafts.csswg.org/css-break/#break-within
And additionally the non-standard "always" value is kept.
=> Test all CSS break-* property values

package.json, result-stats.ts
This PR adds a `results-stats` script that prints basic statistics about a report file's test results.
=> Add "results-stats" script to get data about results files

find-missing-features.ts, package.json, types/types.d.ts
This PR converts the `find-missing-features` script over to TypeScript.
=> Convert find-missing-features to TypeScript

custom-tests.yaml
IE/Edge don't support the pathLength property, leading to false
negatives with this test.
=> Use <stop> instead of <path> for SVGAnimatedNumber custom test

custom-tests.yaml
crypto.subtle.generateKey() returns a promise that resolves to two
keys in a dictionary, so extract one of them.
=> Fix the custom CryptoKey tests

build.js, unittest/unit/build.js
This reverts commit 7f22058493747146d38edb964d83b4f5365aee15, AKA PR #492.  This will help eliminate numerous null results throughout the collector, which should greatly help eliminate bugs in `update-bcd` and eliminate the need for `update-bcd` to do any special tweaks for children when the parent is unsupported.
Partial work towards #2052.
=> Revert "Don't test for "instance in self" for members (#492)"

result-stats.ts
This PR adds a command line argument to the report-stats command to display all of the null results when requested.  This allows us to better eliminate null results.
=> Print null values in stats reports via CLI arg

build.js, custom-tests.yaml, result-stats.ts, static/resources/harness.js, unittest/unit/build.js
This PR removes a bunch of null results from collector results by adding additionaltests and checks.  This fixes #2052.
In results for Chrome 103, I have confirmed that there are no changes of `true` to `false` that result from these changes.
=> Remove more nulls from custom tests

static/resources/harness.js
This PR replaces the `true/false/null` display with `Supported/No Support/Support Unknown` to make it clearer to end users whether a feature is supported or not.
=> Clearly state support vs. true/false/null

custom-tests.yaml
This PR adds a custom test for `location.toString()` and updates the test for the `WorkerLocation` interface to match.
=> Add custom test for Location.toString()

ua-parser.js, unittest/unit/ua-parser.js
This PR updates the ua-parser script to track all Safari 15+ minor versions as individual releases, rather than mapping down (as needed for Samsung Internet and older Safari releases).
=> Track all individual minor versions of Safari 15+

build.js
This PR is a follow-up to #2076.  It seems as though the `targetMembers` object was treated as a different object than the one in the array, so using `indexOf()` does not work.  This PR tweaks the logic to instead filter out any members with a matching name (and make sure that the correct member was actually added).
=> Fix removal of static members when non-static member is present

app.js
This PR fixes the `not using HTTPS` warning.  Apparently `req.secure` was not set to `true` even when using HTTPS.
=> Fix insecure context warning

add-new-bcd.ts
This PR updates the template for the `add-new-bcd` script to automatically mirror derivative browsers, including Oculus, and set IE to false for new features.
=> Update template compat statement for add-new-bcd

add-new-bcd.ts
This PR updates the `add-new-bcd` script to omit adding any features that have been removed from all browsers.  Since they'll eventually be removed again from BCD, there's no point to adding them in the first place.
=> Don't add new BCD for features that have already been removed

unittest/unit/bcd.test.js, unittest/unit/find-missing-features.js, unittest/unit/overrides.test.json, unittest/unit/update-bcd.ts, update-bcd.ts
This PR adds the ability to provide a version range for overrides (ex. `xx-yy`).  This should help with #2239.
=> Allow for version ranges for overrides

build.js
This PR improves the callback detection within the custom tests.  Now, callbacks can be detected as parameters within function calls by looking for `callback,` and `callback)` as well as `callback(`.
=> Improve callback detection

views/index.ejs
The unsecure warning is still displaying even when it shouldn't.  I have a feeling this may be an issue around GAE.  CC @foolip
=> Disable the unsecure warning for now

update-bcd.ts
This PR fixes the handling of mirrored statements to make sure we're mirroring before anything else.  This fixes #2261.
=> Fix updating BCD regarding mirrored statements

ua-parser.js
The `us-parser-js` module identifies the Oculus browser with the name
"Oculus Browser," while the BCD project refers to the browser as
"oculus." Extend the custom parsing logic to perform this translation so
that results captured from the Oculus browser are properly integrated
into BCD.
=> Extend script to update BCD w/results from Oculus

README.md, package.json
This project relies on JSON modules, and that functionality was made
available to Node.js projects in version 16.15.0 [1]. The code cannot be
executed with any earlier release of Node.js (see the sample terminal
output below). Update the project documentation to specify this
requirement.
$ node --version
v16.14.2
$ npm start
> mdn-bcd-collector@6.1.2 start
> node app.js
node:internal/errors:464
ErrorCaptureStackTrace(err);
^
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json" for /tmp/mdn-bcd-collector/node_modules/@mdn/browser-compat-data/data.json
at new NodeError (node:internal/errors:371:5)
at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:87:11)
at defaultGetFormat (node:internal/modules/esm/get_format:102:38)
at defaultLoad …
=> Correct required version of Node.js

custom-tests.yaml
This PR fixes the custom test for the `SVGAnimatedRect` API, following up to https://github.com/mdn/browser-compat-data/pull/17424.
=> Fix custom test for SVGAnimatedRect

overrides.json
This PR adds overrides for `api.FontFaceSetLoadEvent` in response to https://github.com/mdn/browser-compat-data/pull/17365.
=> Add overrides for api.FontFaceSetLoadEvent

static/resources/harness.js
This PR updates the `testObjectName` method of `harness.js` to report what the actual name of an object is when it doesn't match an expected name.
=> Mention what the actual constructor name is if it doesn't match expected

add-new-bcd.ts
This PR updates the `add-new-bcd` script to set `experimental` to `true` by default.  If experimental should be false, the fix script will take care of it.
=> Set experimental to "true" for new features by default

find-missing-results.ts
This PR updates the `find-missing-results` script to ignore IE by default, since we aren't caring about IE data nearly as much.
=> Ignore IE by default in find-missing-results script

build.js, unittest/unit/build.js
This is to avoid adding these features to BCD:
https://github.com/mdn/browser-compat-data/pull/17651
=> Avoid generating tests for [HTMLConstructor] constructors

unittest/unit/bcd.test.js, unittest/unit/find-missing-features.js, unittest/unit/update-bcd.ts, update-bcd.ts
A recent change in the BCD project policy stipulates that information
about feature flags should be removed whenever a feature becomes
supported by default [1]. Modify the `update-bcd` script to honor the
new policy whenever new test results trigger that condition.
Include a test for the case where positive test results are added for a
feature that is already supported via a prefix. This patch intentionally
doesn't change that behavior because prefixes "are part of the web
platform that web developers have to deal with." [2] The test is to
prevent regressions and emphasize the intention.
[1] https://github.com/mdn/browser-compat-data/pull/16637
[2] https://matrix.to/#/!cGYYDEJwjktUBMSTQT:mozilla.org/$JTWeMpzNMULBTZcx-pWFnUNX7DIzE5xPySd70Kpr-MU?via=mozilla.org&via=matrix.org&via=igalia.com) …
=> Remove flag data for default-enabled features

unittest/unit/update-bcd.ts, update-bcd.ts
Because the return value of `update` is used only to optimize I/O, false positives only degrade efficiency--not correctness. However, the underlying behavior substantively effects the interpretation of the `"mirror"` support value. Due to an unrelated bug (where modifications to mirrored support values are not written back to disk), this error cannot currently be observed.
Correct the return value for this condition in order to improve efficiency and prepare for a later correction to the `"mirror"` feature.
=> bcd-update: do not spuriously report modifications

custom-tests.yaml
The interface was not exposed early on, at least Safari 4 has the
methods to create gradients, but the interface object isn't exposed.
=> Add custom test for CanvasGradient

custom-tests.yaml, static/resources/harness.js
I validated this by running the collector locally and comparing the impact it has on the results. Only the results for `document.all` were affected, however, I have not generated a self-signed certificate, so this is only a limited view.
=> Support testing document.all

custom-idl/html.idl
It's supported in Chrome:
https://mdn-bcd-collector.appspot.com/tests/api/MessageEvent/userActivation
=> Add back MessageEvent.userActivation custom IDL

build.js, unittest/unit/build.js
Previously the wrong tests were generated, in particular `@@iterator`
and `forEach` shouldn't be generated.
=> Support async iterators in test generation

custom-idl/webaudio.idl
createConstantSource is on BaseAudioContext (already in BCD) and the
others were renamed in Chrome a decade ago:
https://bugs.chromium.org/p/chromium/issues/detail?id=160176
=> Remove some Web Audio API custom IDL

custom-tests.yaml
This constructor requires two arguments, and the second must be an object whose properties conform to a specific interface:
https://webaudio.github.io/web-audio-api/#AudioProcessingEvent
=> Correct custom test for AudioProcessingEvent

custom-idl/SVG.idl
This PR removes the IDL for SVG features that have been removed from BCD.
=> Remove IDL for SVG features removed from BCD

custom-idl/IndexedDB.idl
This PR removes the IDL definitions for `IDBDatabase.createMutableFile`, which is a proprietary Gecko feature that isn't already in BCD and shouldn't be added to BCD as a result.
=> Remove IDL for proprietary IDBDatabase.createMutableFile

custom-idl/datacue.idl
This PR removes the custom IDL for the proprietary DataCue.data feature.  This feature is not in BCD, and as such should not be added.
=> Remove custom IDL for proprietary DataCue.data

custom-idl/cssom.idl
This PR removes the custom IDL for CSS features that have been removed for BCD or are proprietary features that haven't been added to BCD.
=> Remove IDL for CSS features removed from BCD

custom-idl/mediacapture-streams.idl
This PR removes the custom IDL for the LocalMediaStream API.  This API has been previously removed from BCD.
=> Remove IDL for LocalMediaStream API

custom-idl/mediacapture-fromelement.idl
This PR removes the custom IDL for the CanvaasCaptureMediaStream API.  This API is non-standard and is not presently in BCD, so it should not be added.
=> Remove IDL for CanvasCaptureMediaStream API

custom-idl/html.idl
This PR removes custom IDL for HTML spec features that have been removed from BCD.
=> Remove IDL for HTML features removed from BCD

custom-idl/file-writer-api.idl
This PR removes the IDL for the BlobBuilder API.  This API has previously been removed from BCD.
=> Remove IDL for BlobBuilder

custom-idl/dom.idl
This PR removes custom IDL for DOM features that are either proprietary and not added to BCD, or have been previously removed from BCD.
=> Remove IDL for DOM features removed from BCD

custom-idl/payment-handler.idl
These are still in Chrome, planned to be removed in 111:
https://groups.google.com/a/chromium.org/g/blink-dev/c/AM2bwKxXacQ/m/2V91nC9JHQAJ
=> Add back removed bits of CanMakePaymentEvent as custom IDL

custom-idl/clipboard-apis.idl, custom-idl/html.idl
Use GlobalEventHandlers instead in one case, and for the promise events
just remove the custom IDL as we'd never add anything to BCD for that.
=> Stop using DocumentAndElementEventHandlers

.github/workflows/pull_request.yml
It won't work after https://github.com/foolip/mdn-bcd-collector/pull/2590
and until the ts-node dependency is fixed.
=> Delete production smoke test

custom-tests.yaml
Since tests can now time out to prevent freezing the collector, this can now be enabled.
(cherry picked from commit 03b6ac5f0326f94f1c10174abf450e14bcc39d8d)
=> Re-enable BatteryManager API tests

update-bcd.ts
=> Overhaul code to handle "false" but BCD set to newer version

.eslintrc.json, package-lock.json, package.json, unittest/unit/update-bcd.ts, update-bcd.ts
Pull out the handling to the start of the function rather than inside a
loop, and add types to make the separation between main() and update()
filter arguments a bit clearer. Categories are only used for loading the
data, and the filter is now always a string.
=> Move minimatch logic into update-bcd's update() function

custom-idl/display-locking.idl
It's already on GlobalEventHandlers via @webref/idl.
=> Remove custom IDL for onbeforematch on Element

custom-idl/dom-overlays.idl
It's already on GlobalEventHandlers via @webref/idl.
=> Remove custom IDL for onbeforexrselect on Element

custom-idl/html.idl
This IDL will generate additional tests which could provide information
about what BCD should say if combined with other tests, but as actually
used now they alone would be used and will probaly be wrong.
See https://github.com/foolip/mdn-bcd-collector/issues/2636.
=> Remove custom event handler properties on Element

custom-tests.yaml
These tests were broken because they involved !!document.all, and the
special behavior of the document.all object makes it falsy.
=> Fix HTMLAllCollection custom tests

custom-tests.yaml
createImageBitmap() returns a promise, not an ImageBitmap directly.
=> Fix ImageBitmap custom tests

custom-tests.yaml
This is needed because the interface has the wrong name in Chromium:
https://bugs.chromium.org/p/chromium/issues/detail?id=1404901
=> Add custom tests for InkPresenter

build.ts, custom-idl/file-system-api.idl
The effect of this is to remove the tests for Metadata, which don't work
because this interface has [LegacyNoInterfaceObject] in Chromium.
Writing custom tests is hard because it requires accessing the local
file system and calling getMetadata() on an entry.
=> Handle LegacyNoInterfaceObject

find-missing-features.ts
(cherry picked from commit 419ef18ff65f153e03b50962e4d562b3506bbd7b)
=> Add color to find-missing-results for better visual representation

build.ts, static/resources/harness.js, unittest/unit/build.ts
- Combine testCSSPropertyValue into testCSSProperty
- Greatly simplify CSS property testing
- Remove no-op from build script
- Improve CSS property testing compatibility with older browsers
=> Update CSS property testing
