foolip/mdn-bcd-collector

build.js, package-lock.json, package.json, test/unit/build.js
Diff of generated/ with this change:
```diff
--- a/api/interfaces.html
+++ b/api/interfaces.html
@@ -20490,5 +20490,236 @@ bcd.test('api.XRWebGLLayer.requestViewportScaling', function() {
bcd.test('api.XRWebGLLayer.stencil', function() {
return 'stencil' in XRWebGLLayer.prototype;
});
+bcd.test('api.console', function() {
+  return 'console' in self;
+});
+bcd.test('api.console.assert', function() {
+  return 'assert' in console;
+});
+bcd.test('api.console.clear', function() {
+  return 'clear' in console;
+});
+bcd.test('api.console.count', function() {
+  return 'count' in console;
+});
+bcd.test('api.console.countReset', function() {
+  return 'countReset' in console;
+});
+bcd.test('api.console.debug', function() {
+  return 'debug' in console;
+});
+bcd.test('api.console.dir', …
```
=> Generate tests for IDL namespaces

test/unit/build.js
Anticipating breakage from https://github.com/foolip/mdn-bcd-collector/pull/28.
=> Add tests for methods in buildIDLTests

package-lock.json, package.json
=> Make proxyquire a dev dependency

app.js, tests.js
https://github.com/foolip/mdn-bcd-collector/pull/134
=> Fix lint errors new in eslint-config-google 0.14.0

.eslintrc.js, app.js, build.js, github.js, logger.js, reffy-reports.js, static/resources/harness.js, static/test/test.js, test/app/results.js, test/puppeteer/harness.js, test/unit/build.js, test/unit/github.js, test/unit/storage.js, test/unit/tests.js
This is to unblock https://github.com/foolip/mdn-bcd-collector/pull/176.
=> Disallow trailing commas

github.js, test/unit/github.js
To unblock https://github.com/foolip/mdn-bcd-collector/pull/224.
=> Avoid deprecated use of @octokit/rest (preparing for v17)

github.js, test/unit/github.js
https://github.com/octokit/rest.js/releases/tag/v18.0.0
=> Use octokit.repos.createOrUpdateFileContents() (renamed)

package-lock.json, package.json, test/puppeteer/harness.js
Drop the puppeteer-firefox dependency.
=> Use the experimental `puppeteer.launch({product: 'firefox'})`

.github/workflows/pull_request.yml, .github/workflows/push.yml
Also lint on push, so that breakage is noticed.
=> Combine Lint and Test into a single CI job for PRs

.github/workflows/pull_request.yml, .github/workflows/push.yml
Fixes https://github.com/foolip/mdn-bcd-collector/issues/8.
=> Run Puppeteer tests in CI

.github/workflows/pull_request.yml, .github/workflows/push.yml, package-lock.json, package.json
It's broken and not useful enough to spend time fixing.
=> Drop codecov reporting

.gitignore, app.js, build.js, package-lock.json, package.json, test/app/results.js, test/unit/build.js
This PR adds numerous unittests to cover more lines within the repository.
Before:
File              | % Stmts | % Branch | % Funcs | % Lines
------------------|---------|----------|---------|---------
All files         |   57.94 |    46.77 |   58.82 |   58.43
app.js           |   78.33 |    64.71 |   54.55 |   78.33
build.js         |   40.34 |     38.1 |    43.9 |   40.22
After:
File              | % Stmts | % Branch | % Funcs | % Lines
------------------|---------|----------|---------|---------
All files         |    66.9 (+8.96) |    65.96 (+19.19) |   68.75 (+9.93) |   67.22 (+8.79)
app.js           |     100 (+21.67) |    70.59 (+5.88) |     100 (+45.45) |     100 (+21.67)
build.js         |   51.03 (+10.69) |    61.74 (+23.64) |   52.38 (+8.48) |   50.72 (+10.5)
=> Add more unittests

README.md, test/selenium/selenium.js
This PR introduces adjustments to the Selenium automated testing to improve testing experience.
=> Selenium adjustments

test/selenium/selenium.js
This PR adds the copyright notice to the Selenium script file.
=> Add copyright notice to Selenium script

build.js, test/unit/build.js
This PR adds support for a constructor defined as an ExtAttr as well, and sorts all members after they have all been obtained/generated.
=> Add support for the constructor ExtAttr

test/selenium/selenium.js
Quick fix for the Selenium script.
=> Fix lack of use of proper operator in Selenium runtime

custom-tests.json, static/resources/harness.js
This PR provides two quick fixes: one for a scope tester in harness.js, the other for a test for ANGLE_instanced_arrays.
=> Quick fixes

static/resources/harness.js
Both functions were implemented in Chrome 41.  This PR polyfills them, in the form of creating new functions to not interfere with future testing for JavaScript functionality.
=> Add polyfills for string.includes/startsWith

build.js, custom-tests.json, test/unit/build.js
This PR does a few things to fix test generation:
- Fixes the custom test for ANGLE_instanced_arrays
- Fixes maplike property generation
- Fixes Worker scope tests (add "DedicatedWorker" scope as well)
=> Fix test generation

non-standard.idl
This PR adds a number of new non-standard interfaces and members.
=> Add additional non-standard interfaces

package-lock.json, package.json
This PR bumps the version number to 0.0.5, as well as performs a few package updates for bug fixes.
=> Update to 0.0.5

custom-tests.json
This PR adds a few new custom tests.
=> Add custom tests for AudioBuffer[SourceNode]

DESIGN.md, build.js, custom-tests.json, test/unit/build.js
This PR improves the custom test generation to automatically generate repeated tests for the interface's instance, and its members, thus simplifying the `custom-tests.json` file.
=> Custom test improvements

static/resources/harness.js
This PR resolves a little issue where the status element would not update, by creating an update function that handles if it exists or otherwise.
=> Create updateStatus() function in harness

static/index.html
This PR merges the "all tests" start button with the dropdown and individual test start button, so that there is only one start button on the page.
=> Consolidate homepage

non-standard.idl
=> Exposure sets

static/resources/harness.js
=> Fix status message at end of tests

static/resources/harness.js
=> Fix compiled support test statements

static/resources/harness.js
=> Fix service worker tests

package.json
This PR adds a "clean" command to cleanup generated files.
=> Add "npm run clean"

selenium.js
=> Fix Selenium script

app.js, storage.js
Fixes https://github.com/foolip/mdn-bcd-collector/issues/10.
=> Compute the host based on GAE environment variables

package.json, selenium.js
This PR makes Selenium independent from Mocha, so that we're not dealing with early timeouts due to slower connections or otherwise.
=> Make Selenium independent of Mocha

static/resources/style.css
=> Fix styling

selenium.js
This PR tells the Selenium script to await for specific URLs when running through the page.
=> Selenium: await for URLs

.github/workflows/push.yml, README.md
Fixes https://github.com/foolip/mdn-bcd-collector/issues/466.
=> Make `main` a staging branch, and `prod` the production branch

selenium.js
This PR provides some additional updates to the Selenium script to add more/better logging, such as:
- Collecting console logs from the browser and displaying any errors
- Adds a name to the Selenium tests (so the runs can be found easier in the Selenium server's archives)
- Better catches when the results or the PR fail to submit
=> Selenium script updates

unittest/unit/build.js
Small follow-up to #467 to unittest the new code adjustments.
=> Add unittest for lack of custom constructor test

static/resources/harness.js
Fixes code presented in #482, as the server returns a 201 rather than a 200.
=> harness.js: accept any 2xx code

static/resources/harness.js
Fixes #486.  (Wow, this one's embarrassing...)
=> Fix a typo

selenium.js
This PR updates the Selenium script for better logging and compatibility, as well as better unittesting down the line.  Updates include the following:
- Accommodating for Sauce Labs' odd usage of OSes to differentiate Safari minor versions
- Better handle if logs are unobtainable
=> Update Selenium script

custom-tests.json, package-lock.json, package.json
This PR adjusts custom tests, and bumps the patch version number.
=> Custom tests

custom-idl/dom.idl, custom-idl/non-standard.idl
Matching https://www.w3.org/TR/DOM-Level-3-Core/idl-definitions.html
=> Move two methods from DOMConfiguration to Document

custom-idl/cssom-view.idl, custom-idl/cssom.idl, custom-idl/dom.idl, custom-idl/gamepad.idl, custom-idl/web-bluetooth.idl
Discovered via a work-in-progress validation step for missing types.
=> Fix miscellaneous issues with missing types in custom IDL

build.js, custom-idl/IndexedDB.idl, custom-idl/appmanifest.idl, custom-idl/budget-api.idl, custom-idl/cssom.idl, custom-idl/html.idl, custom-idl/mediacapture-streams.idl, unittest/unit/build.js
Fix some of the simpler cases, and leave TODOs for the rest
=> Validate that all types in Web IDL are known

build.js, unittest/unit/build.js
This PR fixes a bug with the custom test compilation.
=> Recursive import

package.json
This PR configures Prettier to format YAML files as well.
=> Format YAML with Prettier

.github/dependabot.yml
This PR bumps the Dependabot schedule to daily intervals.
=> Change Dependabot schedule to daily

app.js, build.js, github.js, package-lock.json, package.json, selenium.js, unittest/app/app.js, unittest/unit/build.js, unittest/unit/utils.js, utils.js
This PR fixes #489 and closes #468.  With the amount of pull requests generated by Selenium (and the Selenium script I literally wrote to merge them all), I wanted to get this implemented ASAP.
=> Selenium: collect all results

build.js, github.js, package-lock.json, package.json, selenium.js, unittest/unit/github.js, unittest/unit/utils.js, utils.js
This PR provides a number of upgrades to the Selenium script, as well as some of its dependent files.  Namely, it adds a prettier console display, better error handling, and fixes an issue with the filenames.
=> Selenium upgrades

package-lock.json, package.json, update-bcd.js
Fixes https://github.com/foolip/mdn-bcd-collector/issues/531.
=> Let update-bcd.js load and update files individually

utils.js
This PR removes the stringify function, removing the unused sorting portion, and moves the code back into writeFile().
=> Remove unused stringify function

selenium.js
This PR improves the JSON extraction within the Selenium script, using old-fashioned properties and clearing away any prettifying display.
=> Selenium: improve JSON extraction

custom-idl/html.idl
- Add Microdata API custom IDL
- Add HTMLDocument custom IDL
- Add <style disabled> custom IDL
- Add msIsStereo3D custom IDL
=> custom idl

selenium.js
This PR makes a few slight improvements to the Selenium script.
=> Selenium improvements

.github/workflows/pull_request.yml
Context: https://github.com/foolip/mdn-bcd-collector/issues/546
=> Test pull requests on macOS and prepare for Windows

static/resources/harness.js
=> Fix indentation for resource timeout

static/resources/harness.js, static/resources/serviceworker.js, static/resources/sharedworker.js, views/index.ejs
I went the lazy way and just copied runWorker, but I should probably merge those two. Or do you want this as-is, as it seems runServiceWorker is also quite duplicated?
=> Add SharedWorker support

package-lock.json, package.json
This PR bumps the version number to 0.4.0 after merging #550.
=> Bump version number to 0.4.0

views/index.ejs
This PR fixes a few bugs within the JavaScript on the homepage:
- Exposure limitation would always show up and not vanish on CSS property tests
- Exposure limitation was not added on the All Tests selection
=> Fix homepage JavaScript

selenium.js
In a few browser versions (like Internet Explorer), sometimes the report fails to download.  This PR sets up a fallback system to create a GitHub PR if it can't download the report.
=> Fallback to upload to GitHub when report can't download

package.json, update-bcd.js
We already depend on it via eslint.
=> Use fast-deep-equal over own isEquivalent helper

selenium.js, update-bcd.js
This is to suppress log output while running tests:
https://github.com/foolip/mdn-bcd-collector/pull/553
=> Use logger.* over console.* in selenium.js and update-bcd.js

selenium.js
This PR fixes a few issues with the Selenium tests on Safari.
=> Selenium: Always wait page ready when going to new page

custom-tests.json, package-lock.json, package.json
This PR fixes some severe issues with custom tests introduced in the new instance resource updates.
=> Fix custom tests

selenium.js
This PR updates the Selenium script by testing with Windows 10 in all browsers (other than Safari) and testing Opera as well.
=> Selenium updates

static/resources/harness.js, views/tests.ejs
This PR fixes some issues with the DOM hierarchy when displaying results (older Safari versions don't like it when you try to add certain elements to P tags), as well as tosses all the results submission code into feature detection and try-catch clauses.
=> Improve compatibility with older browsers

README.md, find-missing.js, package-lock.json, package.json, scripts.js, selenium.js, update-bcd.js
This PR refactors the executable scripts to use `yargs` to parse arguments, allowing for more flexibility and functionality.
=> Use Yargs for arg parsing

app.js, package-lock.json, package.json, static/resources/style.css, tests.js, views/index.ejs, views/testnotfound.ejs
This PR introduces an updated test 404 page which includes a "Did you mean" section to suggest the correct ident when there's a typo, including caps issues.  This fixes #582.
=> Suggest similar ident if test not found

static/resources/style.css
This PR gives the styling a slight bit of improvement.
=> Improve styling

custom-idl/html.idl
It was a thing:
https://chromium.googlesource.com/chromium/src/+/4312c9f8688669f7adb6a6102cf73e8e58777c8d%5E%21/#F9
=> Add webkitCancelRequestAnimationFrame custom IDL

selenium.js
This PR fixes a few things in the Selenium script.
=> Selenium fixes

app.js, selenium.js, static/resources/harness.js, unittest/app/app.js, views/index.ejs, views/testnotfound.ejs, views/tests.ejs
This PR allows for hiding the results from displaying after the tests.  This improves runtime for the Selenium script.
=> Allow for hiding results

package-lock.json, package.json
This PR bumps the ESLint version up as well as the version number.
=> Bump version number and ESLint version

update-bcd.js
This PR fixes the BCD updater regarding null values, as well as better error display.
=> Fix the BCD updater

build.js, custom-tests.json, unittest/unit/build.js, views/tests.ejs
This PR includes a number of custom tests for CSS features, as well as dynamically includes code to check missing/unimplemented dependencies in custom test imports (a temporary inclusion until `update-bcd` handles them).
=> Custom test additions/improvements

custom-tests.json
This PR adds a custom test that creates an instance of the Element API.
=> Add custom test for Element API

selenium.js
This PR fixes a few issues with the Selenium script.
=> Selenium fix

static/resources/harness.js
=> Post results before displaying them

custom-tests.json
This PR adds additional custom tests.
=> Add additional custom tests

custom-tests.json
This PR adds custom tests for SVG elements.
=> Add tests for SVG elements

custom-tests.json
Also remove some abstract interfaces which can't be created directly but
only serve as base classes for other concrete interfaces.
=> Fix the capitalization of SVG elements in custom tests

package-lock.json, package.json
The `-rc.1` part is specifically to test the new GitHub Action.
=> Bump version number to 0.5.8-rc.1

.github/workflows/push.yml
The pushing of `prod` is proving to be a bit of a headache, so for now, this will just disable it.
=> Remove prod pushing (for now)

static/resources/harness.js
This PR updates the code formatting to include indents in the displayed code, improving legibility.
=> Format code display with indents

custom-tests.json
This PR provides some fixes and updates for the HTML and SVG element support detection for Internet Explorer.
=> Fix HTML/SVG element tests for IE

package-lock.json
This PR performs an update on all of the dependencies, including fixing two high security vulnerabilities.
=> Update dependencies and fix security audits

package.json
This PR configures Nodemon to watch IDL files as well.
=> Include IDL files to rebuild when running start-dev

package.json
This PR fixes the extensions that Nodemon listens to.
=> Fix Nodemon extensions

.nycrc.json, build.js, static/resources/harness.js, static/unittest/index.html, static/unittest/test.js, unittest/unit/find-missing.js
This PR adds additional unittests to ensure our code is functioning as expected.
=> Add additional unittests

static/resources/harness.js
This PR provides a few updates to assist with compatibility.
- Make some if clauses in harness.js consistent
- Update status before loading CSS
- Log every status update to console
=> Compatibility updates

static/resources/style.css, views/index.ejs
- Fix width of known caveats box
- Update feature detection notice
=> Styling fixes

DESIGN.md, build.js, custom-tests.json, static/resources/harness.js, static/resources/serviceworker.js, static/resources/sharedworker.js, static/resources/worker.js
This PR reworks harness.js and build.js to add support for testing promises and other asynchronous tests, reworking the test structure to use callbacks.  Additionally, this adds a custom test for BatteryManager to show proof of concept.
=> Add promise testing support (+ custom test for BatteryManager)

build.js, custom-tests.json
This PR fixes the renaming of the instance variable on promises, as well as enables promise-based tests.
=> Enable promise-based custom tests

static/resources/style.css
Just a few small styling updates.
=> Styling updates

github.js, unittest/unit/github.js
This PR updates the GitHub PR creation to increase details in two ways:
- Adds a PR body that indicates the exact useragent string, browser, digest, and a warning if the PR was created in a dev build
- Adds "(Dev)" to the PR title when created in a dev build
=> Increase details in GitHub PRs

custom-tests.json, static/resources/harness.js, static/resources/serviceworker.js, static/resources/sharedworker.js, static/resources/style.css, static/resources/worker.js, static/unittest/test.js, views/tests.ejs
This PR includes various compatibility improvements that resolve issues with testing in older browser versions.
- Improve styling compatibilty with IE
- Optimize audioContext instance
- Remove redundant console log
- Fix reference
- Start tests if resource loading crashes
- Convert all-test running code into reusable function
- Rename bcd.run() to bcd.go()
- Use JSON stringification and parsing for worker communication
- Stringify result
=> Compatibility improvements

app.js, unittest/app/app.js
Reverts foolip/mdn-bcd-collector#723
=> Revert "Use process.env.npm_package_version vs. require('./package.json').version"

app.js
Staging is having an issue with the build right now, seeing if it's perhaps this.
=> Temporarily disable using git commit as appversion

app.js, selenium.js, views/index.ejs, views/tests.ejs
This PR provides a number of updates regarding the `ignore` list, including implementing it into the Selenium script for certain Chrome versions.
=> Update ignore list param

package-lock.json, package.json, selenium.js
Because what's a CLI script without a little color?﻿
=> Add a little color to some Selenium output

selenium.js
This PR allows for running Selenium non-consecutively via a command line argument.
=> Allow for non-consecutive Selenium runtime

app.js
=> Remove duplicate question mark in did-you-mean

github.js, selenium.js, unittest/unit/github.js, update-bcd.js
Reverts foolip/mdn-bcd-collector#791
=> Revert "Compress results JSON with GZip compression"

custom-tests.json
This PR performs some fixes for the HTML and SVG element APIs, particularly the HTMLQuoteElemenet and all inheriting APIs.
=> Fix custom tests for HTML and SVG element APIs

github.js, ua-parser.js, unittest/unit/github.js, unittest/unit/ua-parser.js
This PR performs a number of updates to the UA parser script, including better integration with the GitHub script.
=> Update UA parser

views/export.ejs, views/layout.ejs
=> Add home link to footer

github.js
This PR fixes the description of GitHub PRs to include the UA string properly.
=> Fix PR descriptions

custom-idl/html.idl
See https://github.com/mdn/browser-compat-data/issues/7519
=> Add additional autocapitalize custom IDL

build.js, custom-idl/aom.idl, custom-tests.json
This PR includes a series of updates to the custom tests, primarily additions.
=> Update custom tests

custom-tests.json
Fixes https://github.com/foolip/mdn-bcd-collector/issues/901.
=> Fix typo in the DOMRectList custom test

custom-css.json, custom-idl/css-animations.idl, custom-idl/css-fonts.idl, custom-idl/cssom.idl, custom-idl/html.idl
Part of https://github.com/foolip/mdn-bcd-collector/issues/917.
=> Add custom CSS/IDL for things found via Confluence

custom-idl/IndexedDB.idl, custom-idl/SVG.idl, custom-idl/clipboard-apis.idl, custom-idl/css-animations.idl, custom-idl/cssom-view.idl, custom-idl/cssom.idl, custom-idl/dom-overlays.idl, custom-idl/dom.idl, custom-idl/encrypted-media.idl, custom-idl/fullscreen.idl, custom-idl/html.idl, custom-idl/mediacapture-streams.idl, custom-idl/selection-api.idl, custom-idl/speech-api.idl, custom-idl/touch-events.idl, custom-idl/wai-aria.idl, custom-idl/webaudio.idl, custom-idl/webkit.idl, custom-idl/webrtc.idl
Part of https://github.com/foolip/mdn-bcd-collector/issues/917.
=> Add custom IDL for more things found via Confluence

build.js, unittest/unit/build.js
Adds these new tests:
api.CustomStateSet.forEach
api.FontFaceSet.forEach
api.GPUAdapterFeatures.forEach
api.Highlight.forEach
api.HighlightsRegister.forEach
api.XRAnchorSet.forEach
=> Add missing forEach member test for IDL setlike declarations

custom-idl/html.idl, custom-idl/intersection-observer.idl, custom-idl/keyboard-event.idl, custom-idl/notifications.idl, custom-idl/uievents.idl
Part of https://github.com/foolip/mdn-bcd-collector/issues/917.
Adds the following new tests:
api.IntersectionObserver.delay
api.IntersectionObserver.trackVisibility
api.IntersectionObserverEntry.isVisible
api.KeyboardEvent.altGraphKey
api.KeyboardEvent.keyLocation
api.MessageEvent.userActivation
api.MouseEvent.initNSMouseEvent
api.MouseEvent.mozInputSource
api.MouseEvent.mozPressure
api.MouseEvent.webkitForce
api.Navigator.getStorageUpdates
api.Navigator.userActivation
api.Notification.get
api.Notification.ondisplay
api.Notification.show
api.UIEvent.rangeOffset
api.UIEvent.rangeParent
api.UserActivation
api.UserActivation.hasBeenActive
api.UserActivation.isActive
=> Add ever more custom IDL from Confluence

package-lock.json, package.json
New tests since 1.3.1:
api.CSSScrollTimelineRule.scrollOffsets
api.RTCRtpReceiver.transform
api.RTCRtpScriptTransform
api.RTCRtpScriptTransform.RTCRtpScriptTransform
api.RTCRtpSender.transform
api.SFrameTransform
api.SFrameTransform.SFrameTransform
api.SFrameTransform.readable
api.SFrameTransform.setEncryptionKey
api.SFrameTransform.writable
api.ScrollTimeline.scrollOffsets
api.TrustedHTML.toJSON
api.TrustedScript.toJSON
api.TrustedScriptURL.toJSON
api.XRCompositionLayer.mipLevels
api.XRProjectionLayer.fixedFoveation
Removed tests:
api.CSSScrollTimelineRule.end
api.CSSScrollTimelineRule.start
api.ScrollTimeline.end
api.ScrollTimeline.start
api.VideoTrackReader
api.VideoTrackReader.VideoTrackReader
api.VideoTrackReader.onended
api.VideoTrackReader.readyState
api.VideoTrackReader.start …
=> Release 1.3.2

custom-tests.json
For https://github.com/mdn/browser-compat-data/pull/9084.
=> Test BaseAudioContext members using an AudioContext instance

app.js
Following the suggestion in http://expressjs.com/en/guide/error-handling.html
Express also uses NODE_ENV to hide the stack trace in production.
=> Simplify error handling in express request handlers

build.js, unittest/unit/build.js
Prefixed variants are now done via custom IDL and CSS. update-bcd.js
isn't able to map those back to the prefixed entries in BCD, then also
isn't able to do that for the mechanism now deleted.
This doesn't change the build tests.json at all because it was unused.
=> Drop support for building prefixed variants of tests

build.js, static/resources/harness.js, unittest/unit/build.js, unittest/unit/tests.js
Follow-up to https://github.com/foolip/mdn-bcd-collector/pull/984.
=> Drop the empty string prefixes from tests.json

static/resources/harness.js, views/export.ejs, views/index.ejs, views/layout.ejs, views/tests.ejs
This was inconsistently applied, and not needed in HTML.
=> Remove XML-style <br /> self-closing tags

selenium.js
This doesn't change the resulting list of browsers to test at all, but
avoids mixing string and number versions and doing arithmetic with them.
Also undo some odd Prettier formatting.
=> Use compare-versions in selenium.js

custom-idl/DOM-Parsing.idl
This probably isn't supported anywhere...
=> Add custom IDL for XMLSerializer.serializeToStream method

README.md
Part of https://github.com/foolip/mdn-bcd-collector/issues/1000.
=> Document how to use the update-bcd script

README.md, add-new-bcd.js, unittest/unit/update-bcd.js, update-bcd.js
Fixes https://github.com/foolip/mdn-bcd-collector/issues/1000.
=> Add --release argument (filter) for update-bcd.js

build.js, unittest/unit/build.js
This has no effect on the built tests.json.
=> Simplify compileTest internally

README.md, app.js
Fixes https://github.com/foolip/mdn-bcd-collector/issues/986.
=> Support running a HTTPS server locally with a custom certificate

find-missing.js
This reveals a lot of missing tests, as well as a lot of bad data in
BCD.
=> Add a --include-aliases option to the find-missing script

static/resources/style.css
This PR is a minor update to the styling for buttons, select dropdowns, and submit buttons, performing the following:
- Applying the same pseudo-class styles as a regular button to submit buttons (hover, disabled)
- Ensuring disabled select dropdowns have the proper styling when not hovering
=> Update button/select/submit styling

package-lock.json, package.json
Added tests:
api.FontMetadata.style
api.GPURenderPassEncoder.setBlendConstant
api.GPUSupportedFeatures
api.GPUSupportedFeatures.entries
api.GPUSupportedFeatures.forEach
api.GPUSupportedFeatures.has
api.GPUSupportedFeatures.keys
api.GPUSupportedFeatures.size
api.GPUSupportedFeatures.values
api.HTMLBodyElement.ongamepadconnected
api.HTMLBodyElement.ongamepaddisconnected
api.HTMLFrameSetElement.ongamepadconnected
api.HTMLFrameSetElement.ongamepaddisconnected
api.HighlightRegistry.get
api.HighlightRegistry.set
api.NamedFlowMap.clear
api.NamedFlowMap.entries
api.NamedFlowMap.forEach
api.NamedFlowMap.keys
api.NamedFlowMap.size
api.NamedFlowMap.values
api.NavigatorUAData.platform
api.SVGSVGElement.ongamepadconnected
api.SVGSVGElement.ongamepaddisconnected
Removed tests: …
=> Release 3.0.1

build.js, unittest/unit/build.js
=> Drop support for [Constructor] extended attribute

package-lock.json, package.json
Added test: api.HTMLPortalElement.HTMLPortalElement
Many tests also have their global exposure changed.
=> Release 3.0.2

custom-tests.json
Helps with https://github.com/mdn/browser-compat-data/pull/10129.
=> Use webkitSpeechRecognition to test SpeechRecognition members

package-lock.json, package.json
https://github.com/foolip/mdn-bcd-collector/pull/1132 has changed all
CSS property tests, the the minor version is bumped.
Added tests:
api.AnimationEffect.after
api.AnimationEffect.before
api.AnimationEffect.nextSibling
api.AnimationEffect.parent
api.AnimationEffect.previousSibling
api.AnimationEffect.remove
api.AnimationEffect.replace
api.AnimationNodeList
api.AnimationNodeList.item
api.AnimationNodeList.length
api.AnimationTimeline.play
api.AudioData
api.AudioData.AudioData
api.AudioData.allocationSize
api.AudioData.clone
api.AudioData.close
api.AudioData.copyTo
api.AudioData.duration
api.AudioData.numberOfChannels
api.AudioData.numberOfFrames
api.AudioData.sampleFormat
api.AudioData.sampleRate
api.AudioData.timestamp
api.CanvasRenderingContext2D.fontKerning …
=> Release 3.1.0

custom-idl/geometry.idl, ua-parser.js
Point to a commit for WebKit source, since it can change.
=> Update a few URLs to master branches already renamed to main

package-lock.json, package.json
Added tests:
api.CSSColorValue.colorSpace
api.CSSColorValue.to
api.CSSDeviceCMYK
api.CSSDeviceCMYK.CSSDeviceCMYK
api.CSSDeviceCMYK.alpha
api.CSSDeviceCMYK.c
api.CSSDeviceCMYK.k
api.CSSDeviceCMYK.m
api.CSSDeviceCMYK.y
api.EncodedAudioChunk.byteLength
api.EncodedAudioChunk.copyTo
api.EncodedVideoChunk.byteLength
api.EncodedVideoChunk.copyTo
api.GPUDevice.importExternalTexture
api.GPUExternalTexture
api.GPUExternalTexture.label
api.XRWebGLLayer.fixedFoveation
Removed tests:
api.CSSColorValue.toColor
api.CSSColorValue.toGray
api.CSSColorValue.toHSL
api.CSSColorValue.toHWB
api.CSSColorValue.toLCH
api.CSSColorValue.toLab
api.CSSColorValue.toRGB
api.CSSGray
api.CSSGray.CSSGray
api.CSSGray.alpha
api.CSSGray.gray
api.Document.addressSpace
api.EncodedAudioChunk.data
api.EncodedVideoChunk.data …
=> Release 3.1.1

custom-idl/SVG.idl
Added tests:
api.SVGSVGElement.zoomAndPan
api.SVGViewElement.zoomAndPan
api.SVGViewSpec
api.SVGViewSpec.zoomAndPan
=> Add custom IDL for zoomAndPan attributes

package-lock.json, package.json
Added tests:
api.Blob.webkitSlice
api.OffscreenCanvasRenderingContext2D.createConicGradient
api.PaintRenderingContext2D.createConicGradient
api.SVGSVGElement.zoomAndPan
api.SVGViewElement.zoomAndPan
api.SVGViewSpec
api.SVGViewSpec.zoomAndPan
No other tests were removed or modified.
=> Release 3.1.2

custom-tests.json
Part of https://github.com/foolip/mdn-bcd-collector/issues/1163
=> Avoid hardcoded appspot.com URLs in custom tests

package-lock.json, package.json
Added tests:
api.ReceiveStream.remoteReset
api.SendStream.remoteCanceled
api.SendStream.reset
api.VisualViewport.segments
css.properties.print-color-adjust
Removed tests:
api.ReceiveStream.abortReading
api.ReceiveStream.readingAborted
api.SendStream.abortWriting
api.SendStream.writingAborted
=> Release 3.1.3

package-lock.json, package.json
Includes https://github.com/foolip/mdn-bcd-collector/pull/1189 and no
other interesting changes.
=> Release 3.1.4

custom-tests.json
Reverts foolip/mdn-bcd-collector#1200
=> Revert "Add reusable instances of Worker and SharedWorker"

custom-tests.json
To help with https://github.com/mdn/browser-compat-data/pull/11050.
=> Create an instance for XMLHttpRequest tests

package-lock.json, package.json
Notable changes:
https://github.com/foolip/mdn-bcd-collector/pull/1236
https://github.com/foolip/mdn-bcd-collector/pull/1237
https://github.com/foolip/mdn-bcd-collector/pull/1238
Added tests:
api.CSSMathClamp.lower
api.CSSMathClamp.upper
api.CSSMathClamp.value
api.DatagramDuplexStream.incomingHighWaterMark
api.DatagramDuplexStream.incomingMaxAge
api.DatagramDuplexStream.outgoingHighWaterMark
api.DatagramDuplexStream.outgoingMaxAge
api.GPUPresentationContext
api.GPUPresentationContext.configure
api.GPUPresentationContext.getCurrentTexture
api.GPUPresentationContext.getPreferredFormat
api.GPUPresentationContext.unconfigure
css.properties.input-security
Removed tests:
api.CSSMathClamp.max
api.CSSMathClamp.min
api.CSSMathClamp.val
api.GPUCanvasContext
api.GPUCanvasContext.configureSwapChain …
=> Release 3.1.7

custom-tests.json
To help with https://github.com/mdn/browser-compat-data/pull/11140.
=> Add custom code for WheelEvent instance

package-lock.json, package.json
Notable changes:
https://github.com/foolip/mdn-bcd-collector/pull/1245
https://github.com/foolip/mdn-bcd-collector/pull/1246
https://github.com/foolip/mdn-bcd-collector/pull/1247
https://github.com/foolip/mdn-bcd-collector/pull/1248
https://github.com/foolip/mdn-bcd-collector/pull/1249
https://github.com/foolip/mdn-bcd-collector/pull/1251
https://github.com/foolip/mdn-bcd-collector/pull/1252
Added tests:
api.Document.onwebkitpointerlockchange
api.Document.onwebkitpointerlockerror
api.Document.webkitExitPointerLock
api.Document.webkitPointerLockElement
api.Element.webkitRequestPointerLock
api.WebKitAnimationEvent.animationName
api.WebKitAnimationEvent.elapsedTime
api.WebKitAnimationEvent.pseudoElement
api.WebKitTransitionEvent.elapsedTime
api.WebKitTransitionEvent.propertyName …
=> Release 3.1.8

package-lock.json, package.json
Added tests:
api.AnimationTimeline.duration
api.FontMetadata.italic
api.FontMetadata.stretch
api.FontMetadata.weight
api.GPUSupportedLimits.maxComputePerDimensionDispatchSize
api.GPUSupportedLimits.maxComputeWorkgroupInvocations
api.GPUSupportedLimits.maxComputeWorkgroupStorageSize
api.GPUSupportedLimits.maxInterStageShaderComponents
api.GPUSupportedLimits.minStorageBufferOffsetAlignment
api.GPUSupportedLimits.minUniformBufferOffsetAlignment
api.HTMLMetaElement.media
api.ML
api.ML.createContext
api.MLContext
api.MLGraph
api.MLGraph.compute
api.MLGraphBuilder
api.MLGraphBuilder.MLGraphBuilder
api.MLGraphBuilder.abs
api.MLGraphBuilder.add
api.MLGraphBuilder.averagePool2d
api.MLGraphBuilder.batchNormalization
api.MLGraphBuilder.build
api.MLGraphBuilder.ceil
api.MLGraphBuilder.clamp …
=> Release 3.1.9

custom-idl/SVG.idl
This reverts most of commit f17e718694be5ce201e7b3042424ea324cdcac16.
=> Add back custom IDL now gone from @webref/idl

package-lock.json, package.json
Added tests:
api.CanvasRenderingContext2D.roundRect
api.Crypto.randomUUID
api.Element.setHTML
api.GPUCanvasContext
api.GPUCanvasContext.canvas
api.GPUCanvasContext.configure
api.GPUCanvasContext.getCurrentTexture
api.GPUCanvasContext.getPreferredFormat
api.GPUCanvasContext.unconfigure
api.MLGraphBuilder.elu
api.MLGraphBuilder.hardSigmoid
api.MLGraphBuilder.linear
api.MLGraphBuilder.softplus
api.MLGraphBuilder.softsign
api.MLOperator
api.Navigator.pdfViewerEnabled
api.OffscreenCanvasRenderingContext2D.roundRect
api.PaintRenderingContext2D.roundRect
api.Path2D.roundRect
api.Sanitizer.getConfiguration
api.Sanitizer.getDefaultConfiguration
api.Sanitizer.sanitizeFor
api.VideoFrame.allocationSize
api.VideoFrame.codedRect
api.VideoFrame.copyTo
api.VideoFrame.visibleRect
Removed tests: …
=> Release 3.1.11

build.js, custom-js.json
Some WebAssembly constructors that require too much setup are left
untested.
=> Generate test for JavaScript constructors

package-lock.json, package.json
This release adds 588 tests for JavaScript builtins:
javascript.builtins.AggregateError
javascript.builtins.AggregateError.AggregateError
javascript.builtins.Array
javascript.builtins.Array.@@iterator
javascript.builtins.Array.@@species
javascript.builtins.Array.@@unscopables
javascript.builtins.Array.Array
javascript.builtins.Array.at
javascript.builtins.Array.concat
javascript.builtins.Array.copyWithin
javascript.builtins.Array.entries
javascript.builtins.Array.every
javascript.builtins.Array.fill
javascript.builtins.Array.filter
javascript.builtins.Array.find
javascript.builtins.Array.findIndex
javascript.builtins.Array.flat
javascript.builtins.Array.flatMap
javascript.builtins.Array.forEach
javascript.builtins.Array.from
javascript.builtins.Array.includes …
=> Release 3.2.0 (JavaScript builtins!)

package-lock.json, package.json
Added tests:
javascript.builtins.Atomics.wake
javascript.builtins.Set.keys
javascript.builtins.String.contains
javascript.builtins.String.trimLeft
javascript.builtins.String.trimRight
Removed tests:
javascript.builtins.Function.displayName
=> Release 3.2.1

build.js
Fixes #1316 (and my comments on mdn/browser-compat-data#11561 and mdn/browser-compat-data#11562)
=> Cover inherited attributes

package.json
Added tests:
api.DOMMatrix.a
api.DOMMatrix.b
api.DOMMatrix.c
api.DOMMatrix.d
api.DOMMatrix.e
api.DOMMatrix.f
api.DOMMatrix.m11
api.DOMMatrix.m12
api.DOMMatrix.m13
api.DOMMatrix.m14
api.DOMMatrix.m21
api.DOMMatrix.m22
api.DOMMatrix.m23
api.DOMMatrix.m24
api.DOMMatrix.m31
api.DOMMatrix.m32
api.DOMMatrix.m33
api.DOMMatrix.m34
api.DOMMatrix.m41
api.DOMMatrix.m42
api.DOMMatrix.m43
api.DOMMatrix.m44
api.DOMPoint.w
api.DOMPoint.x
api.DOMPoint.y
api.DOMPoint.z
api.DOMRect.height
api.DOMRect.width
api.DOMRect.x
api.DOMRect.y
api.PaymentRequestEvent.instrumentKey
=> Release 3.2.2

build.js, unittest/unit/build.js
It has now been lowercased in BCD.
=> Remove mapping of console->Console

update-bcd.js
Fixes https://github.com/foolip/mdn-bcd-collector/issues/1331.
=> Combine results from different reports for the same browser version

custom-js.json
Test verified working with Chrome Canary.
=> Add a test for Object.hasOwn()

package-lock.json, package.json
Added tests:
api.MLGraphBuilder.hardSwish
api.XRSession.frameRate
api.XRSession.onframeratechange
api.XRSession.supportedFrameRates
api.XRSession.updateTargetFrameRate
javascript.builtins.Object.hasOwn
Removed test: api.SendStream
Renamed tests: api.Console -> api.console
=> Release 3.2.3

package-lock.json, package.json
Lots of custom tests have been modified:
https://github.com/foolip/mdn-bcd-collector/pull/1346
https://github.com/foolip/mdn-bcd-collector/pull/1355
https://github.com/foolip/mdn-bcd-collector/pull/1357
https://github.com/foolip/mdn-bcd-collector/pull/1358
https://github.com/foolip/mdn-bcd-collector/pull/1364
https://github.com/foolip/mdn-bcd-collector/pull/1367
https://github.com/foolip/mdn-bcd-collector/pull/1375
Added tests:
api.BaseAudioContext.decodeAudioData.promise_syntax
api.CanvasRenderingContext2D.drawImage.SVGImageElement_source_image
api.Document.createElement.options
api.Document.createElementNS.options
api.Document.documentURI.readonly
api.WebTransportError
api.WebTransportError.WebTransportError
api.WebTransportError.applicationProtocolCode
api.Window.reportError …
=> Release 3.2.4

static/resources/harness.js
This PR introduces some console logging we can enable or disable as needed to track down buggy, misbehaving custom tests.  I use this pretty frequently when test results aren't working as expected, and figured it makes sense to put it into the code with a toggleable variable.
=> Add debug mode console logs

.eslintrc.json, .prettierrc, DESIGN.md, add-new-bcd.js, app.js, build.js, exporter.js, find-missing-features.js, logger.js, results.js, scripts.js, selenium.js, storage.js, ua-parser.js, update-bcd.js
This PR adds rules to Prettier to synchronize the two linters better.
=> Synchronize ESLint and Prettier rules

package-lock.json, package.json
- Custom Tests
- Additions
- XMLHttpRequestEventTarget
- XMLHttpRequestUpload
- Updates
- Make Plugin test inconclusive if navigator.plugins is empty
- Speed up CryptoKey tests with reusable instance
- Re-disable BatteryManager test
- Add debug mode console logs
- Add find-missing-results script
- Update webref IDL and CSS (2.2.10 -> 2.2.11 and 2.0.6 -> 2.0.7 respectively)
=> Release 3.2.5

static/resources/harness.js
- Add debugging logging for when result isn't boolean/null
- Include option to log test completions
=> Add further debug logging in debug mode

static/resources/harness.js
This PR fixes an issue with the new debugmode logging caused by Prettier formatting.﻿
=> Fix new debugmode logging

package-lock.json, package.json
This PR fixes the URL generation using `location.protocol` and `location.host`.  (This should be the last patch release regarding this issue.)﻿
=> Release 3.2.9

custom-idl/css-animations.idl, custom-idl/css-transitions.idl, custom-idl/uievents.idl
Fixes https://github.com/foolip/mdn-bcd-collector/issues/1414.
=> Add initWebKitAnimationEvent and initWebKitTransitionEvent tests

views/index.ejs, views/layout.ejs
Fixes #1410 
This PR will fix all of the Accessibility and SEO audit warnings provided from Lighthouse. The last issue is the color contrast for the buttons nested in the `<form id="test-form">` element. We can handle that after some discussion as there are a few routes we can choose to resolve that last audit warning.
The SEO score will be 100 and after the color contrast is fixed, the Accessibility will also be 100! 🎉
=> Addressing Lighthouse audit report

package-lock.json, package.json
Added tests:
api.CanvasRenderingContext2D.isContextLost
api.ContactAddress.addressLine
api.ContactAddress.city
api.ContactAddress.country
api.ContactAddress.dependentLocality
api.ContactAddress.organization
api.ContactAddress.phone
api.ContactAddress.postalCode
api.ContactAddress.recipient
api.ContactAddress.region
api.ContactAddress.sortingCode
api.ContactAddress.toJSON
api.Document.oncontextlost
api.Document.oncontextrestored
api.GPUAdapter.isFallbackAdapter
api.HTMLElement.oncontextlost
api.HTMLElement.oncontextrestored
api.MathMLElement.oncontextlost
api.MathMLElement.oncontextrestored
api.OffscreenCanvas.oncontextlost
api.OffscreenCanvas.oncontextrestored
api.OffscreenCanvasRenderingContext2D.isContextLost
api.PaintRenderingContext2D.isContextLost …
=> Release 3.2.10

custom-tests.yaml
Addresses review comments in https://github.com/foolip/mdn-bcd-collector/pull/1409#discussion_r692946179.  Closes #1424, closes #1425.﻿
=> Add comment explaining the RTCPeerConnection constructor test

package-lock.json, package.json
Added tests:
api.HTMLElement.virtualKeyboardPolicy
api.MediaSource.canConstructInDedicatedWorker
api.Navigator.virtualKeyboard
api.VirtualKeyboard
api.VirtualKeyboard.boundingRect
api.VirtualKeyboard.hide
api.VirtualKeyboard.ongeometrychange
api.VirtualKeyboard.overlaysContent
api.VirtualKeyboard.show
=> Release 3.2.12

custom-tests.yaml
This PR creates a custom base test for the `DOMTokenList` API based upon the discussion in https://github.com/mdn/browser-compat-data/pull/12138#pullrequestreview-738770447.﻿
=> Create custom tests for DOMTokenList

custom-tests.yaml
Reverts foolip/mdn-bcd-collector#1459
=> Revert "Create custom test for RTCRtpReceiver"

custom-tests.yaml
Addresses https://github.com/foolip/mdn-bcd-collector/pull/1469#issuecomment-915051834.﻿
=> Add comment explaining RTCPeerConnection constructor order

static/resources/style.css, views/index.ejs
Just a nice little thing to include on the homepage!﻿
=> Add a privacy notice to homepage

custom-tests.yaml
Like https://github.com/foolip/mdn-bcd-collector/pull/1375.
=> Add a type string for more event constructors

CHANGELOG.md, release.js
https://www.nodegit.org/api/revwalk/
Also remove dates from the changelog since they aren't included in the
summary by default, and aren't really useful to add either.
=> Use NodeGit's Revwalk to generate the changelog

CHANGELOG.md, package-lock.json, package.json
Release v4.0.0, generated by `release.js`.
=> Release 4.0.0

package-lock.json
This PR fixes one final audit issue that had slipped through the gaps last time, most likely due to the recent package upgrades we merged.
=> Run npm audit fix (again)

custom-idl/cssom.idl, custom-idl/custom-state-pseudo-class.idl, custom-idl/file-system-api.idl, custom-idl/manifest-incubations.idl, custom-idl/mediacapture-transform.idl, custom-idl/webcodecs.idl
This PR adds custom IDL for the features in BCD we are not generating tests for.
=> Add IDL for missing features in BCD

static/resources/harness.js
=> Don't render results automatically when there are more than 250

custom-tests.yaml
This PR fixes #1691 by adding custom tests for the speech synthesis APIs.﻿
=> Add custom tests for speech synthesis

ua-parser.js
This PR fixes the bug reported in #1891.
=> Ensure site doesn't crash if OS can't be parsed from UA

README.md
Follow-up to https://github.com/foolip/mdn-bcd-collector/pull/1685
=> Update README about deployment

selenium.js
This PR randomizes the selection of Selenium hosts when running the Selenium script, rather than simply hammering the first host with all the tests.
=> Randomize selection of Selenium host

build.js
Extracted from https://github.com/foolip/mdn-bcd-collector/pull/1228.
=> Simplify LegacyFactoryFunction code

custom-idl/priority-hints.idl
See https://github.com/mdn/browser-compat-data/pull/15946
=> Add all-lowercase fetchpriority attributes custom IDL

release.js
This PR fixes the changelog as pointed out in https://github.com/foolip/mdn-bcd-collector/pull/1977/files#r864867100.
=> Fix changelog

selenium.js
Reverts foolip/mdn-bcd-collector#1919.  Due to the variation of results between CTs, it's not a good idea to mix results if we can help it.
=> Revert "Randomize selection of Selenium host"

package-lock.json, package.json
=> Install fdir

.eslintignore, .github/workflows/pull_request.yml, .prettierignore
This PR adds a step to clone BCD when performing PR tests.  Required to land #2039.
=> Clone browser-compat-data in PR test workflow

update-bcd.js
This PR updates the `update-bcd` script to account for mirrored support by performing mirroring, comparing the results, and making updates if needed.
=> update-bcd: account for mirroring

custom-tests.yaml
This PR adds a custom test for the CSSNamespaceRule API.
=> Add custom test for CSSNamespaceRule

find-missing-results.ts, selenium.js
- Don't include Oculus in missing results
- Set Firefox options according to Firefox version
=> Various tweaks

results.js
This PR sorts the test results in results files to ensure that results output is consistent.  This should ensure that Selenium runs remain consistent.
=> Sort results

style.scss, views/browserinfo.ejs, views/index.ejs, views/layout.ejs
This PR adds the detected browser info to the top of the homepage for better visibility.
=> Display browser info at top of homepage

result-stats.ts
This PR updates the `result-stats` script to allow for querying the status of a specific feature to determine its support.  This is useful for debugging.
Additionally, this PR performs a few other smaller tweaks, such as adding colors to logging output, and removing a leftover debugging statement.
=> Allow for querying features in a report

custom-tests.yaml
This PR adds checks to confirm that an interface exists before attempting to construct it.  This will eliminate many nulls throughout our data.  Part of work towards #2052.
=> Check if interface exists before attempting to construct

CHANGELOG.md, package-lock.json, package.json
Forked from #2170.  Changes were significant enough for a minor release.
=> Release 6.1.0

build.js, find-missing-results.ts, selenium.js, static/resources/harness.js, unittest/puppeteer/harness.js, update-bcd.ts
This finishes https://github.com/foolip/mdn-bcd-collector/issues/432.
=> Improve formatting of if statements

custom-tests.yaml
Resolves the issue found in https://github.com/mdn/browser-compat-data/pull/17361.
=> Fix EventSource constructor test

style.scss
This PR adds the `color-scheme` property to the styling.
=> Add color-scheme property

.github/workflows/release.yml
Fixes https://github.com/foolip/mdn-bcd-collector/issues/2023.
=> Stop creating release PRs automatically

custom-idl/SVG.idl, custom-idl/css-typed-om.idl, custom-idl/html.idl
These custom tests helped sort out the BCD data, but no longer serve any
purpose.
=> Remove custom IDL related to resolved BCD issues

DESIGN.md
As of 2021-08-02 [1], this project has maintained custom tests in YAML
format. Update the design documentation accordingly.
6ec933aab151f2c389312de5cc8f349e50a72866
=> Reformat examples in design document

update-bcd.ts
The Array iterator enumerates the requisite values.
=> Simplify loop

custom-idl/html.idl, custom-idl/screen-capture.idl
This PR removes the custom IDL that has been added to Webref, as well as fixes any issues related to it.
=> Remove duplicate IDL

custom-idl/html.idl, custom-idl/screen-capture.idl
Reverts foolip/mdn-bcd-collector#2306
=> Revert "Remove duplicate IDL"

custom-tests.yaml
This PR adds a custom test for the Worklet API, inspired by https://github.com/mdn/browser-compat-data/pull/17694.
=> Add custom test for Worklet API

build.js, unittest/unit/build.js
Fixes https://github.com/foolip/mdn-bcd-collector/issues/2366.
=> Fix custom tests for symbols

custom-tests.yaml
There are some required dictionary members here.
=> Fix speech synthesis event custom tests

custom-idl/selection-api.idl, custom-idl/service-workers.idl, custom-idl/uievents.idl, custom-idl/webaudio.idl, custom-idl/xhr.idl
This PR removes the custom IDL for features that are either proprietary features that shouldn't be added to BCD, or have been removed from BCD already.
=> Remove IDL for proprietary features not in BCD or removed from BCD

custom-js.json
https://groups.google.com/a/chromium.org/g/blink-dev/c/ptKolvGLGWY/m/_18d7JS9AQAJ
=> Add tests for methods that change Array and TypedArray by copy

README.md, package.json
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/a9b3057a50d2e03f8d20d59c5b54e36144a72d08.
=> Replace start-dev with dev to match Yari

app.js
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/b4bff1dfa2ed8e9d2c57cd6e61cda696d70297c1.
=> Use GITHUB_TOKEN from env variables if not available in secrets.json

app.js, views/export.ejs
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/c6a03fdbef32a9f310f9eac7ab375ba337522ad8.
=> Improve GitHub export error catching

app.js
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/ca5dfaefe2ea0ca3f3905e62e7431c9784373a42.
=> Trim trailing newline in dev version

custom-tests.yaml
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/c9b8840286e5d719406421f006ef739dc5f4c255.
=> Add custom tests for Geolocation APIs

build.js, custom-tests.yaml
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/73b21975ec6f3ba08c05f0bf77ff26255ab0978b.
=> Add custom tests for file system APIs

custom-tests.yaml
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/c27a1d7cccf348368fb13d6e5223705747e171ca.
=> Fallback to legacy getUserMedia for MediaStream instance

custom-tests.yaml
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/430e7c96a1f15276ebbf7ba52b665106b355b8d5.
=> Replace >- with |- in custom-tests.yml

custom-tests.yaml
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/537fb22230d160ef0fa4a77727f51ce67de662bb.
=> Add custom test for MutationRecord API

release.ts, tsconfig.json
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/57ff245798a1c98f5e0856b6126a44ecd908bccf.
=> Fix TypeScript for release script

app.ts, views/index.ejs, views/unsecurewarning.ejs
- Show insecure context warning when not using HTTPS
- Use local JavaScript to determine if secure context
=> Show warning when not using HTTPS

README.md, selenium.ts
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/2c6a9b408d88018ff1602b071e2b800e51eaf544.
=> Update Selenium script to add "since" argument

app.ts, build.ts, custom-idl/index.ts, exporter.ts, logger.ts, prepare-resources.ts, release.ts, results.ts, selenium-keepalive.ts, selenium.ts, storage.ts, tests.ts, ua-parser.ts, unittest/app/app.ts, unittest/puppeteer/harness.ts, unittest/unit/add-new-bcd.ts, unittest/unit/bcd.test.ts, unittest/unit/build.ts, unittest/unit/exporter.ts, unittest/unit/find-missing-features.ts, unittest/unit/results.ts, unittest/unit/storage.ts, unittest/unit/tests.ts, unittest/unit/ua-parser.ts, unittest/unit/update-bcd.ts
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/7e99c5abd363a15cb55424b659ff5d09e1042a66.
=> Fix copyright comments

.prettierrc, static/resources/harness.js, static/unittest/test.js
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/a257883443e6f67635e44e964b9e17ec27ffd08e.
=> Update Prettier config and format

lib/selenium-keepalive.ts, selenium.ts
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/3287b5d9728472a38277b5cb509104ce8e2c5c0f.
=> Move selenium-keepalive to lib folder

lib/exec.ts
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/6899ae3dac8ee0586dfe1e0ae48247e93255c436.
=> Fix exec function

nodemon.json
Cherry-picked from https://github.com/GooborgStudios/mdn-bcd-collector/commit/7d69bc3eca1504ff0db842b3b16a3319dedde24c.
=> Fix Nodemon ignores

static/resources/harness.js
(cherry picked from commit 87e3be4b0015167a3aebec52326d3a98995aff91)
=> Allow debugmode to be turned on easier

custom-tests.yaml
(cherry picked from commit 3c8c4a22ab725c162830271eca7088f4228d2251)
=> Add timeout to GeolocationPosition test

static/resources/harness.js
(cherry picked from commit c5b314188936e90d4cbe90d3208b50aebd28ff4c)
=> Improve debugging

static/resources/harness.js
- Add test timeout
- Fix test timeout handler
=> Add 10s test timeout to harness.js

add-new-bcd.ts
(cherry picked from commit e7926b548e377d580fc7b439480119f36a8e4141)
=> Run fix script after adding new BCD

views/tests.ejs, views/unsecurewarning.ejs
- Show unsecure warning on test page as well
- Ensure that unsecure warning only shows in production
=> Update HTTPS warning

static/resources/harness.js
(cherry picked from commit 581f26ff15aed756f1330b2ff0d1bbd809629196)
=> Handle additional constructor error message

static/resources/harness.js
(cherry picked from commit eecd43b8d0a09cd29e206f495cea719bed73d016)
=> Update to latest highlight.js

.eslintrc.json, app.ts, lib/exec.ts, lib/selenium-keepalive.ts, package-lock.json, package.json, update-bcd.ts
(cherry picked from commit eaec4b869aa613490faf1b800d53af2792dcb20f)
=> Enforce node: protocol in imports

find-missing-features.ts
(cherry picked from commit 59868b93a58924721c31b190f0ab7c6c4651ed66)
=> Add output to clarify direction of find-missing-features

custom-js.json
(cherry picked from commit f9b2d4eaad55c844e03b3aa60bee6e727aee9c26)
=> Add custom test for Function.prototype.name

DESIGN.md, custom-tests.yaml, unittest/lib/exporter.ts, unittest/unit/update-bcd.ts
This is intended to reduce differences between forks.
=> Replace the appspot.com URL wherever possible

README.md, update-bcd.ts
(cherry picked from commit f54ce14b49f2211a6a188687af14591b369a523e)
=> Improve update-bcd script

README.md
(cherry picked from commit d753220b032232c6d35cfa8ab1cc1722989e0df7)
=> Mention v6.1.1 UA change in "Reviewing BCD changes"

README.md
(cherry picked from commit 55de9b5ff31ff1197c0694e0ce45682306639e90)
=> Update "Minor Safari version changes" section

update-bcd.ts
- Fix update-bcd release filter
- Update description for update-bcd release argument
- Fix release filtering
=> Update update-bcd release filtering

overrides.json
- Add override for ApplicationCache API
- Add additional overrides
- Add overrides for referrerPolicy properties
=> Add overrides

custom-idl/FileAPI.idl, custom-tests.yaml
- Add custom test for Clipboard API
- Add custom test for Client API
- Add custom test for FeaturePolicy API
- Add custom test for api.PerformanceEntry.toJSON
- Improve tests for CSSConditionRule and CSSGroupingRule
- Add custom test for PaintWorklet; fall back to PaintWorklet for Worklet if AudioWorklet unavailable
- Add custom test for URLSearchParams
- Add custom test for api.CanvasRenderingContext2D.drawImage.ImageBitmap_source_image
- Improve test for api.CanvasRenderingContext2D.drawImage.SVGImageElement_source_image
- Fix CanvasRenderingContext2D resource list
- Fix test for CSPViolationReportBody
- Add custom test for DOMMatrix
- Improve custom test for ImageBitmap
- Add custom tests for method/constructor parameters
- Add additional custom tests
- Add additional custom tests
- …
=> Add custom tests

selenium.ts
(cherry picked from commit 94d12a131aefb104f5994b469dd0534504273910)
=> Set default "since" argument to 2020

custom-css.json
(cherry picked from commit f3988259eea2b3607dcfd757d72c5bb2c83cf3ea)
=> Fix test for css.properties.-moz-orient.inline_and_block

static/resources/harness.js, views/index.ejs
(cherry picked from commit 32aabb797ed10932b53247173c39181342a660e7)
=> Drop IE support

build.ts, unittest/sample/custom-tests.test.yaml, unittest/unit/build.ts
- Filter out alt. names for Document.characterSet
- Filter out alt. name for Window.navigator
=> Filter out alt. names

static/resources/harness.js
(cherry picked from commit b75eb77482091237088b93527c7f35f6998900c3)
=> Update bcd.testOptionParam to test functions/constructors

build.ts, unittest/unit/build.ts
- Format custom test code with Prettier (again)
- Update unittests following Prettier formatting and other changes
=> Format custom test code with Prettier (again)

static/resources/harness.js
(cherry picked from commit c9372238764d40ae9043003cb531c1dd33df93e0)
=> Allow for defining other options while using testOptionParam()

static/resources/harness.js
(cherry picked from commit d5c207310a4e7c7083c3203e12d5df48e62e146f)
=> Expose string.includes() polyfill to tests

static/resources/harness.js
- Document bcd.testObjectName()
- Add self-documentation to bcd.testObjectName() results
- Document all of harness.js
=> Document harness.js

build.ts
(cherry picked from commit 99b68761d0c6db0a293355edc65f2286e33c71c4)
=> Improve Prettier failure catch

add-new-bcd.ts
(cherry picked from commit 1938a84e00c29dc59c08577062999a2cf5995750)
=> Import orderFeatures function directly from BCD

.c8rc.json, lib/exec.ts, prepare-resources.ts, unittest/unit/add-new-bcd.ts
- Add unittest for recursiveAdd function
- Update sections to ignore codecov
=> More unittests and coverage changes

views/unsecurewarning.ejs
- Make unsecure context warning a link to secure context
- Unsecure warning: point to specific page
- Avoid hardcoding deployment domain into unsecure warning link
=> Update unsecure warning

style.scss, views/layout.ejs
(cherry picked from commit 87cd118fdcc5ea99d7a13a8e8c5816ecdc20ee51)
=> Handle notch / Dynamic Island on iPhone

static/resources/harness.js
(cherry picked from commit 55d187f302a09f0a9745c3ed5862cd27893c4f16)
=> Add non-invasive polyfill for Array.isArray()

build.ts, unittest/unit/build.ts
(cherry picked from commit 8f23515e8d203b878178bb8f9bc874f3235bfccf)
=> Ignore event handlers; don't generate tests for events yet

release.ts
(cherry picked from commit e9b08df793994e31bb059b870e2f2cffae547af9)
=> Fix which build command is called in the release script
